import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from database.db_manager import initialize_db, add_recipe

initialize_db()

recipes = [
    {
        'name': 'Ratatouille Provençale',
        'description': 'Un grand classique de la cuisine provençale, coloré et savoureux, à base de légumes d\'été mijotés à l\'huile d\'olive.',
        'history': 'Plat traditionnel de Provence, la ratatouille était autrefois un plat de paysans qui utilisaient les légumes de leur jardin.',
        'author': 'Tradition provençale',
        'cuisine_type': 'Française',
        'region': 'Provence',
        'occasion': 'Quotidien',
        'dish_type': 'Plat principal',
        'category': 'Ragoût',
        'diet': 'Vegan',
        'ideal_season': 'Été',
        'prep_time': 25,
        'cook_time': 45,
        'rest_time': 0,
        'difficulty': 'Facile',
        'servings': 4,
        'estimated_cost': '€',
        'calories_per_serving': 180,
        'proteins': 4,
        'carbs': 20,
        'fats': 10,
        'fiber': 6,
        'sugar': 12,
        'salt': 1.2,
        'cooking_type': 'Mijoté',
        'fridge_duration': '3 jours',
        'freezer_duration': '3 mois',
        'reheating_method': 'Casserole à feu doux ou micro-ondes',
        'tags': ['été', 'vegan', 'légumes', 'provençal', 'sans gluten'],
        'aromatic_profile': 'Herbacé, méditerranéen',
        'texture': 'Fondant',
        'ingredients': [
            {'name': 'aubergine', 'quantity': 2, 'unit': 'pièce', 'preparation': 'coupée en cubes'},
            {'name': 'courgette', 'quantity': 2, 'unit': 'pièce', 'preparation': 'coupée en rondelles'},
            {'name': 'poivron rouge', 'quantity': 1, 'unit': 'pièce', 'preparation': 'coupé en lanières'},
            {'name': 'poivron jaune', 'quantity': 1, 'unit': 'pièce', 'preparation': 'coupé en lanières'},
            {'name': 'tomate', 'quantity': 4, 'unit': 'pièce', 'preparation': 'coupée en dés'},
            {'name': 'oignon', 'quantity': 2, 'unit': 'pièce', 'preparation': 'émincé'},
            {'name': 'ail', 'quantity': 3, 'unit': 'gousse', 'preparation': 'haché'},
            {'name': 'huile d\'olive', 'quantity': 4, 'unit': 'cuillère à soupe'},
            {'name': 'thym', 'quantity': 2, 'unit': 'branche'},
            {'name': 'basilic', 'quantity': 1, 'unit': 'botte', 'preparation': 'ciselé', 'optional': True},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Faire revenir l\'oignon et l\'ail dans l\'huile d\'olive à feu moyen pendant 5 minutes.', 'duration': 5, 'technique': 'Saisir'},
            {'step_number': 2, 'description': 'Ajouter les poivrons et cuire 5 minutes supplémentaires.', 'duration': 5, 'technique': 'Sauté'},
            {'step_number': 3, 'description': 'Incorporer les aubergines et les courgettes, mélanger et cuire 10 minutes.', 'duration': 10, 'technique': 'Mijoter'},
            {'step_number': 4, 'description': 'Ajouter les tomates, le thym, saler, poivrer. Couvrir et laisser mijoter 30 minutes à feu doux.', 'duration': 30, 'technique': 'Mijoter'},
            {'step_number': 5, 'description': 'Parsemer de basilic frais avant de servir.', 'duration': 2, 'technique': 'Émincer'},
        ],
        'equipment': ['Casserole', 'Couteau de chef', 'Planche à découper'],
        'allergens': [],
        'tips': [
            {'tip_type': 'astuces', 'content': 'Faire dégorger les aubergines avec du sel 30 min avant pour enlever l\'amertume.'},
            {'tip_type': 'astuces', 'content': 'La ratatouille est encore meilleure réchauffée le lendemain.'},
            {'tip_type': 'accompagnements', 'content': 'Riz basmati'},
            {'tip_type': 'accompagnements', 'content': 'Pain grillé à l\'huile d\'olive'},
            {'tip_type': 'accords', 'content': 'Rosé de Provence'},
            {'tip_type': 'variantes', 'content': 'Version gratin : ajouter du fromage de chèvre et passer au four 15 min.'},
        ],
    },
    {
        'name': 'Poulet Rôti aux Herbes',
        'description': 'Un poulet rôti doré et croustillant, parfumé aux herbes fraîches et à l\'ail, incontournable du dimanche.',
        'cuisine_type': 'Française',
        'region': 'France entière',
        'occasion': 'Repas de famille',
        'dish_type': 'Plat principal',
        'category': 'Rôtissage',
        'diet': 'Standard',
        'ideal_season': 'Toutes saisons',
        'prep_time': 15,
        'cook_time': 75,
        'rest_time': 10,
        'difficulty': 'Facile',
        'servings': 4,
        'estimated_cost': '€€',
        'calories_per_serving': 380,
        'proteins': 42,
        'carbs': 2,
        'fats': 22,
        'cooking_type': 'Rôtissage',
        'oven_temperature': 200,
        'fridge_duration': '2 jours',
        'freezer_duration': '2 mois',
        'tags': ['rôti', 'dimanche', 'famille', 'poulet'],
        'texture': 'Croustillant dehors, fondant dedans',
        'ingredients': [
            {'name': 'poulet entier', 'quantity': 1.5, 'unit': 'kg'},
            {'name': 'beurre', 'quantity': 50, 'unit': 'g', 'preparation': 'ramolli'},
            {'name': 'ail', 'quantity': 4, 'unit': 'gousse'},
            {'name': 'thym', 'quantity': 3, 'unit': 'branche'},
            {'name': 'romarin', 'quantity': 2, 'unit': 'branche'},
            {'name': 'citron', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'huile d\'olive', 'quantity': 2, 'unit': 'cuillère à soupe'},
            {'name': 'sel', 'quantity': 1, 'unit': 'cuillère à café'},
            {'name': 'poivre', 'quantity': 1, 'unit': 'au goût'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Préchauffer le four à 200°C. Mélanger le beurre ramolli avec l\'ail haché, le thym et le romarin.', 'duration': 5, 'temperature': 200},
            {'step_number': 2, 'description': 'Glisser le beurre aux herbes sous la peau du poulet et en frotter l\'extérieur. Saler et poivrer.', 'duration': 5},
            {'step_number': 3, 'description': 'Placer le citron coupé en deux et une gousse d\'ail à l\'intérieur du poulet.', 'duration': 2},
            {'step_number': 4, 'description': 'Enfourner 1h15 en arrosant toutes les 20 minutes avec le jus de cuisson.', 'duration': 75, 'temperature': 200, 'technique': 'Rôtissage'},
            {'step_number': 5, 'description': 'Laisser reposer 10 minutes sous du papier alu avant de découper.', 'duration': 10},
        ],
        'equipment': ['Four', 'Plat à rôtir', 'Couteau de chef'],
        'allergens': ['Lactose'],
        'tips': [
            {'tip_type': 'astuces', 'content': 'Pour une peau encore plus croustillante, sécher le poulet avec du papier absorbant avant de le beurrer.'},
            {'tip_type': 'astuces', 'content': 'Vérifier la cuisson avec un thermomètre : 75°C à cœur.'},
            {'tip_type': 'accompagnements', 'content': 'Pommes de terre rôties'},
            {'tip_type': 'accompagnements', 'content': 'Haricots verts'},
            {'tip_type': 'accords', 'content': 'Bourgogne blanc ou Chardonnay'},
        ],
    },
    {
        'name': 'Tarte Tatin aux Pommes',
        'description': 'La célèbre tarte renversée aux pommes caramélisées, dorée et fondante, née d\'un heureux accident dans un hôtel de Sologne.',
        'history': 'Créée par les sœurs Tatin à Lamotte-Beuvron au XIXe siècle, cette tarte est devenue l\'un des desserts français les plus célèbres.',
        'author': 'Sœurs Tatin',
        'cuisine_type': 'Française',
        'region': 'Sologne',
        'occasion': 'Fête',
        'dish_type': 'Dessert',
        'category': 'Pâtisserie',
        'diet': 'Végétarien',
        'ideal_season': 'Automne',
        'prep_time': 20,
        'cook_time': 40,
        'rest_time': 10,
        'difficulty': 'Intermédiaire',
        'servings': 6,
        'estimated_cost': '€€',
        'calories_per_serving': 320,
        'proteins': 3,
        'carbs': 48,
        'fats': 14,
        'sugar': 32,
        'cooking_type': 'Rôtissage',
        'oven_temperature': 180,
        'fridge_duration': '2 jours',
        'tags': ['automne', 'dessert', 'pommes', 'caramel', 'classique'],
        'texture': 'Fondant, caramélisé',
        'aromatic_profile': 'Caramel, beurre, pomme',
        'ingredients': [
            {'name': 'pomme', 'quantity': 1.2, 'unit': 'kg', 'preparation': 'pelées, épépinées, coupées en quartiers', 'quality': 'Golden ou Reinette'},
            {'name': 'beurre', 'quantity': 80, 'unit': 'g'},
            {'name': 'sucre', 'quantity': 150, 'unit': 'g'},
            {'name': 'pâte brisée', 'quantity': 1, 'unit': 'pièce', 'replacement': 'pâte feuilletée'},
            {'name': 'cannelle', 'quantity': 1, 'unit': 'cuillère à café', 'optional': True},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Préchauffer le four à 180°C. Dans un moule à tatin ou une poêle allant au four, faire fondre le beurre et le sucre à feu moyen jusqu\'à obtenir un caramel doré.', 'duration': 10, 'temperature': 0, 'technique': 'Mijoter'},
            {'step_number': 2, 'description': 'Disposer les quartiers de pommes debout en cercle serré dans le caramel. Cuire 10 minutes sur feu moyen.', 'duration': 10, 'technique': 'Saisir'},
            {'step_number': 3, 'description': 'Couvrir les pommes avec la pâte brisée en rentrant les bords. Enfourner 30 minutes jusqu\'à ce que la pâte soit dorée.', 'duration': 30, 'temperature': 180, 'technique': 'Rôtissage'},
            {'step_number': 4, 'description': 'Laisser reposer 10 minutes puis renverser sur un plat de service.', 'duration': 10},
        ],
        'equipment': ['Four', 'Moule à tarte', 'Couteau de chef'],
        'allergens': ['Gluten', 'Lactose', 'Œufs'],
        'tips': [
            {'tip_type': 'astuces', 'content': 'Retourner rapidement dès la sortie du four pour éviter que le caramel durcisse.'},
            {'tip_type': 'astuces', 'content': 'Servir tiède avec une boule de glace vanille ou de la crème fraîche.'},
            {'tip_type': 'erreurs', 'content': 'Ne pas attendre trop longtemps avant de démouler.'},
            {'tip_type': 'accords', 'content': 'Cidre brut de Normandie'},
            {'tip_type': 'accords', 'content': 'Calvados (en digestif)'},
        ],
    },
    {
        'name': 'Soupe à l\'Oignon Gratinée',
        'description': 'Une soupe réconfortante aux oignons longuement caramélisés, gratinée avec du gruyère fondu sur des croûtons de pain.',
        'cuisine_type': 'Française',
        'region': 'Île-de-France',
        'occasion': 'Quotidien',
        'dish_type': 'Entrée',
        'category': 'Soupe',
        'diet': 'Végétarien',
        'ideal_season': 'Hiver',
        'prep_time': 15,
        'cook_time': 60,
        'difficulty': 'Facile',
        'servings': 4,
        'estimated_cost': '€',
        'calories_per_serving': 280,
        'proteins': 12,
        'carbs': 30,
        'fats': 12,
        'cooking_type': 'Mijoté',
        'oven_temperature': 220,
        'fridge_duration': '2 jours',
        'tags': ['hiver', 'soupe', 'réconfort', 'fromage', 'gratinée'],
        'texture': 'Fondant, croustillant (croûtons)',
        'ingredients': [
            {'name': 'oignon', 'quantity': 1, 'unit': 'kg', 'preparation': 'émincé finement'},
            {'name': 'beurre', 'quantity': 40, 'unit': 'g'},
            {'name': 'farine', 'quantity': 1, 'unit': 'cuillère à soupe'},
            {'name': 'bouillon de bœuf', 'quantity': 1.5, 'unit': 'l', 'replacement': 'bouillon de légumes'},
            {'name': 'vin blanc sec', 'quantity': 15, 'unit': 'cl'},
            {'name': 'pain de campagne', 'quantity': 8, 'unit': 'tranche'},
            {'name': 'gruyère', 'quantity': 150, 'unit': 'g', 'preparation': 'râpé'},
            {'name': 'thym', 'quantity': 2, 'unit': 'branche'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Faire fondre le beurre dans une grande casserole. Ajouter les oignons émincés et les cuire à feu doux pendant 30-40 minutes en remuant régulièrement jusqu\'à ce qu\'ils soient bien dorés et caramélisés.', 'duration': 40, 'technique': 'Mijoter'},
            {'step_number': 2, 'description': 'Ajouter la farine, mélanger 1 minute. Déglacer avec le vin blanc et laisser évaporer 2 minutes.', 'duration': 3, 'technique': 'Déglacer'},
            {'step_number': 3, 'description': 'Verser le bouillon, ajouter le thym, saler, poivrer. Cuire 20 minutes à feu doux.', 'duration': 20},
            {'step_number': 4, 'description': 'Faire griller les tranches de pain au four. Répartir la soupe dans des bols allant au four, déposer 2 croûtons et couvrir de gruyère râpé.', 'duration': 5},
            {'step_number': 5, 'description': 'Passer sous le gril du four à 220°C pendant 5 minutes jusqu\'à gratinage doré.', 'duration': 5, 'temperature': 220, 'technique': 'Gratiner'},
        ],
        'equipment': ['Casserole', 'Bols à soupe allant au four', 'Four'],
        'allergens': ['Gluten', 'Lactose'],
        'tips': [
            {'tip_type': 'astuces', 'content': 'La longue caramélisation des oignons est le secret de cette soupe : ne pas se presser !'},
            {'tip_type': 'astuces', 'content': 'Utiliser des bols en céramique qui tiennent bien la chaleur.'},
            {'tip_type': 'accords', 'content': 'Vin blanc de Bourgogne'},
        ],
    },
    {
        'name': 'Quiche Lorraine',
        'description': 'La vraie quiche lorraine à base de lardons fumés, d\'œufs et de crème fraîche dans une pâte brisée croustillante.',
        'cuisine_type': 'Française',
        'region': 'Lorraine',
        'occasion': 'Brunch',
        'dish_type': 'Plat principal',
        'category': 'Quiche',
        'diet': 'Standard',
        'ideal_season': 'Toutes saisons',
        'prep_time': 20,
        'cook_time': 35,
        'rest_time': 10,
        'difficulty': 'Facile',
        'servings': 6,
        'estimated_cost': '€',
        'calories_per_serving': 420,
        'proteins': 16,
        'carbs': 22,
        'fats': 30,
        'cooking_type': 'Rôtissage',
        'oven_temperature': 180,
        'fridge_duration': '2 jours',
        'tags': ['lorraine', 'lardons', 'tarte salée', 'brunch', 'classique'],
        'ingredients': [
            {'name': 'pâte brisée', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'lardon fumé', 'quantity': 200, 'unit': 'g'},
            {'name': 'œuf', 'quantity': 3, 'unit': 'pièce'},
            {'name': 'crème fraîche épaisse', 'quantity': 25, 'unit': 'cl'},
            {'name': 'gruyère râpé', 'quantity': 80, 'unit': 'g', 'optional': True},
            {'name': 'muscade', 'quantity': 1, 'unit': 'pincée'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Préchauffer le four à 180°C. Foncer un moule à tarte avec la pâte brisée et piquer le fond à la fourchette. Réfrigérer 10 min.', 'duration': 10, 'temperature': 180},
            {'step_number': 2, 'description': 'Faire revenir les lardons à sec dans une poêle jusqu\'à légère coloration. Égoutter sur papier absorbant.', 'duration': 5, 'technique': 'Saisir'},
            {'step_number': 3, 'description': 'Dans un bol, battre les œufs avec la crème, saler légèrement, poivrer, ajouter la muscade.', 'duration': 3},
            {'step_number': 4, 'description': 'Répartir les lardons sur le fond de tarte, verser l\'appareil crème-œufs, saupoudrer de gruyère.', 'duration': 3},
            {'step_number': 5, 'description': 'Enfourner 30-35 minutes jusqu\'à ce que la quiche soit dorée et légèrement gonflée.', 'duration': 35, 'temperature': 180},
        ],
        'equipment': ['Four', 'Moule à tarte', 'Poêle', 'Saladier'],
        'allergens': ['Gluten', 'Lactose', 'Œufs'],
        'tips': [
            {'tip_type': 'astuces', 'content': 'Ne pas trop saler : les lardons le sont déjà.'},
            {'tip_type': 'erreurs', 'content': 'Ne pas ouvrir le four pendant la cuisson pour éviter que la quiche retombe.'},
            {'tip_type': 'accompagnements', 'content': 'Salade verte'},
            {'tip_type': 'accords', 'content': 'Riesling d\'Alsace'},
        ],
    },
    {
        'name': 'Bœuf Bourguignon',
        'description': 'Un ragoût de bœuf mijoté au vin rouge de Bourgogne avec des champignons, des carottes et des lardons. Un plat emblématique de la cuisine française.',
        'history': 'Plat paysan bourguignon à l\'origine, popularisé dans le monde entier par Julia Child.',
        'cuisine_type': 'Française',
        'region': 'Bourgogne',
        'occasion': 'Repas de famille',
        'dish_type': 'Plat principal',
        'category': 'Ragoût',
        'diet': 'Standard',
        'ideal_season': 'Hiver',
        'prep_time': 30,
        'cook_time': 150,
        'difficulty': 'Intermédiaire',
        'servings': 6,
        'estimated_cost': '€€€',
        'calories_per_serving': 480,
        'proteins': 38,
        'carbs': 18,
        'fats': 24,
        'cooking_type': 'Braisage',
        'fridge_duration': '3 jours',
        'freezer_duration': '3 mois',
        'tags': ['hiver', 'bœuf', 'vin rouge', 'mijoté', 'bourgogne'],
        'texture': 'Fondant, savoureux',
        'aromatic_profile': 'Vineux, herbacé, champignon',
        'ingredients': [
            {'name': 'bœuf à braiser', 'quantity': 1.2, 'unit': 'kg', 'preparation': 'coupé en gros cubes', 'quality': 'paleron ou macreuse'},
            {'name': 'vin rouge de Bourgogne', 'quantity': 75, 'unit': 'cl'},
            {'name': 'lardon fumé', 'quantity': 150, 'unit': 'g'},
            {'name': 'carotte', 'quantity': 3, 'unit': 'pièce', 'preparation': 'en rondelles'},
            {'name': 'oignon', 'quantity': 2, 'unit': 'pièce', 'preparation': 'émincé'},
            {'name': 'champignon de Paris', 'quantity': 300, 'unit': 'g'},
            {'name': 'ail', 'quantity': 3, 'unit': 'gousse'},
            {'name': 'bouquet garni', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'farine', 'quantity': 2, 'unit': 'cuillère à soupe'},
            {'name': 'beurre', 'quantity': 30, 'unit': 'g'},
            {'name': 'huile', 'quantity': 2, 'unit': 'cuillère à soupe'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Faire dorer les lardons dans la cocotte avec un peu de beurre. Réserver.', 'duration': 5, 'technique': 'Saisir'},
            {'step_number': 2, 'description': 'Dans la même cocotte, faire revenir les cubes de bœuf sur toutes les faces jusqu\'à bonne coloration. Réserver.', 'duration': 10, 'technique': 'Saisir'},
            {'step_number': 3, 'description': 'Faire revenir les oignons et les carottes 5 minutes. Saupoudrer de farine et mélanger.', 'duration': 5},
            {'step_number': 4, 'description': 'Remettre la viande et les lardons. Verser le vin, ajouter l\'ail et le bouquet garni. Saler, poivrer. Porter à ébullition puis laisser mijoter à couvert 2h30 à feu très doux.', 'duration': 150, 'technique': 'Braisage'},
            {'step_number': 5, 'description': 'Faire sauter les champignons dans le beurre et les ajouter 20 minutes avant la fin.', 'duration': 5, 'technique': 'Sauté'},
        ],
        'equipment': ['Cocotte en fonte', 'Couteau de chef', 'Planche à découper'],
        'allergens': ['Gluten', 'Lactose'],
        'tips': [
            {'tip_type': 'astuces', 'content': 'Encore meilleur réchauffé le lendemain. Préparer la veille si possible.'},
            {'tip_type': 'astuces', 'content': 'Utiliser un bon vin que vous boiriez volontiers (le vin bon marché donne un résultat médiocre).'},
            {'tip_type': 'accompagnements', 'content': 'Pommes de terre vapeur'},
            {'tip_type': 'accompagnements', 'content': 'Tagliatelles fraîches'},
            {'tip_type': 'accords', 'content': 'Pinot Noir de Bourgogne'},
        ],
    },
    {
        'name': 'Crème Brûlée à la Vanille',
        'description': 'Un dessert élégant à la crème onctueuse parfumée à la vanille, recouvert d\'une fine couche de caramel craquant.',
        'cuisine_type': 'Française',
        'region': 'France',
        'occasion': 'Dîner romantique',
        'dish_type': 'Dessert',
        'category': 'Pâtisserie',
        'diet': 'Végétarien',
        'ideal_season': 'Toutes saisons',
        'prep_time': 15,
        'cook_time': 40,
        'rest_time': 120,
        'difficulty': 'Intermédiaire',
        'servings': 4,
        'estimated_cost': '€€',
        'calories_per_serving': 380,
        'proteins': 6,
        'carbs': 28,
        'fats': 28,
        'sugar': 26,
        'cooking_type': 'Vapeur',
        'oven_temperature': 150,
        'fridge_duration': '2 jours',
        'tags': ['dessert', 'vanille', 'crème', 'élégant', 'classique'],
        'texture': 'Crémeux, fondant, croustillant (caramel)',
        'aromatic_profile': 'Vanille, caramel',
        'ingredients': [
            {'name': 'crème liquide entière', 'quantity': 50, 'unit': 'cl'},
            {'name': 'jaune d\'œuf', 'quantity': 5, 'unit': 'pièce'},
            {'name': 'sucre', 'quantity': 80, 'unit': 'g'},
            {'name': 'vanille', 'quantity': 1, 'unit': 'gousse', 'quality': 'gousse de Madagascar'},
            {'name': 'cassonade', 'quantity': 4, 'unit': 'cuillère à soupe', 'preparation': 'pour caraméliser'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Préchauffer le four à 150°C. Fendre la gousse de vanille, gratter les graines et les mettre dans la crème. Chauffer la crème sans bouillir.', 'duration': 10, 'temperature': 0},
            {'step_number': 2, 'description': 'Fouetter les jaunes d\'œufs avec le sucre jusqu\'à blanchissement.', 'duration': 5, 'technique': 'Fouetter'},
            {'step_number': 3, 'description': 'Verser la crème chaude sur les jaunes en mélangeant doucement. Filtrer et répartir dans des ramequins.', 'duration': 5},
            {'step_number': 4, 'description': 'Cuire au bain-marie au four à 150°C pendant 35-40 minutes. La crème doit être prise mais encore légèrement tremblotante au centre.', 'duration': 40, 'temperature': 150},
            {'step_number': 5, 'description': 'Laisser refroidir puis réfrigérer au moins 2 heures. Avant de servir, saupoudrer de cassonade et caraméliser au chalumeau.', 'duration': 5, 'technique': 'Gratiner'},
        ],
        'equipment': ['Four', 'Ramequins', 'Saladier', 'Fouet', 'Chalumeau de cuisine'],
        'allergens': ['Lactose', 'Œufs'],
        'tips': [
            {'tip_type': 'astuces', 'content': 'Pour un caramel parfait, saupoudrer finement et passer le chalumeau en mouvement circulaire.'},
            {'tip_type': 'erreurs', 'content': 'Ne pas trop cuire : la crème doit rester tremblotante à la sortie du four.'},
            {'tip_type': 'accords', 'content': 'Sauternes ou Champagne'},
        ],
    },
    {
        'name': 'Salade Niçoise',
        'description': 'Une salade fraîche et colorée originaire de Nice, avec thon, olives, anchois et légumes croquants de Méditerranée.',
        'cuisine_type': 'Française',
        'region': 'Côte d\'Azur',
        'occasion': 'Quotidien',
        'dish_type': 'Plat principal',
        'category': 'Salade',
        'diet': 'Sans gluten',
        'ideal_season': 'Été',
        'prep_time': 20,
        'cook_time': 15,
        'difficulty': 'Facile',
        'servings': 4,
        'estimated_cost': '€€',
        'calories_per_serving': 320,
        'proteins': 24,
        'carbs': 18,
        'fats': 16,
        'fiber': 4,
        'tags': ['été', 'salade', 'méditerranéen', 'thon', 'niçoise', 'sans gluten'],
        'texture': 'Croquant, frais',
        'ingredients': [
            {'name': 'thon en boîte', 'quantity': 200, 'unit': 'g', 'preparation': 'égoutté'},
            {'name': 'tomate', 'quantity': 4, 'unit': 'pièce', 'preparation': 'en quartiers'},
            {'name': 'œuf', 'quantity': 4, 'unit': 'pièce', 'preparation': 'durs, coupés en deux'},
            {'name': 'haricot vert', 'quantity': 200, 'unit': 'g', 'preparation': 'cuits al dente'},
            {'name': 'pomme de terre', 'quantity': 300, 'unit': 'g', 'preparation': 'cuites, en rondelles'},
            {'name': 'olive noire de Nice', 'quantity': 80, 'unit': 'g'},
            {'name': 'anchois', 'quantity': 8, 'unit': 'filet', 'optional': True},
            {'name': 'poivron', 'quantity': 1, 'unit': 'pièce', 'preparation': 'émincé'},
            {'name': 'huile d\'olive', 'quantity': 4, 'unit': 'cuillère à soupe'},
            {'name': 'vinaigre de vin', 'quantity': 1, 'unit': 'cuillère à soupe'},
            {'name': 'basilic', 'quantity': 1, 'unit': 'botte'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Cuire les œufs durs 10 minutes. Cuire les haricots verts 5 minutes à l\'eau bouillante salée, refroidir dans l\'eau glacée.', 'duration': 15},
            {'step_number': 2, 'description': 'Préparer la vinaigrette : mélanger huile d\'olive, vinaigre, sel, poivre.', 'duration': 2},
            {'step_number': 3, 'description': 'Disposer harmonieusement tous les ingrédients dans un grand plat. Arroser de vinaigrette et garnir de basilic frais.', 'duration': 5},
        ],
        'equipment': ['Saladier', 'Casserole'],
        'allergens': ['Œufs', 'Poisson'],
        'tips': [
            {'tip_type': 'astuces', 'content': 'La vraie salade niçoise n\'est jamais mélangée mais dressée avec soin.'},
            {'tip_type': 'astuces', 'content': 'Utiliser du thon à l\'huile d\'olive de qualité.'},
            {'tip_type': 'accords', 'content': 'Rosé de Provence bien frais'},
            {'tip_type': 'variantes', 'content': 'Version végétarienne : remplacer le thon par des pois chiches.'},
        ],
    },
    {
        'name': 'Gratin Dauphinois',
        'description': 'Un gratin de pommes de terre fondantes, cuites lentement dans la crème et l\'ail, emblème de la cuisine dauphinoise.',
        'cuisine_type': 'Française',
        'region': 'Dauphiné',
        'occasion': 'Repas de famille',
        'dish_type': 'Plat principal',
        'category': 'Grillades',
        'diet': 'Végétarien',
        'ideal_season': 'Hiver',
        'prep_time': 20,
        'cook_time': 75,
        'difficulty': 'Facile',
        'servings': 6,
        'estimated_cost': '€',
        'calories_per_serving': 360,
        'proteins': 8,
        'carbs': 35,
        'fats': 22,
        'cooking_type': 'Rôtissage',
        'oven_temperature': 160,
        'fridge_duration': '2 jours',
        'tags': ['hiver', 'gratin', 'pommes de terre', 'crème', 'réconfort', 'dauphiné'],
        'texture': 'Fondant, gratiné',
        'ingredients': [
            {'name': 'pomme de terre', 'quantity': 1.2, 'unit': 'kg', 'preparation': 'pelées, en rondelles fines', 'quality': 'à chair ferme (Charlotte)'},
            {'name': 'crème liquide entière', 'quantity': 40, 'unit': 'cl'},
            {'name': 'lait entier', 'quantity': 20, 'unit': 'cl'},
            {'name': 'ail', 'quantity': 2, 'unit': 'gousse'},
            {'name': 'beurre', 'quantity': 20, 'unit': 'g'},
            {'name': 'muscade', 'quantity': 1, 'unit': 'pincée'},
            {'name': 'gruyère râpé', 'quantity': 50, 'unit': 'g', 'optional': True},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Préchauffer le four à 160°C. Frotter le plat à gratin avec une gousse d\'ail coupée, puis beurrer.', 'duration': 3, 'temperature': 160},
            {'step_number': 2, 'description': 'Chauffer la crème et le lait avec l\'ail haché, la muscade, sel et poivre. Ne pas bouillir.', 'duration': 5},
            {'step_number': 3, 'description': 'Disposer les rondelles de pommes de terre en couches dans le plat. Verser le mélange crème-lait chaud par-dessus.', 'duration': 10},
            {'step_number': 4, 'description': 'Enfourner 1h15 à 160°C. Les pommes de terre doivent être fondantes et le dessus doré. Couvrir de gruyère les 15 dernières minutes si désiré.', 'duration': 75, 'temperature': 160, 'technique': 'Rôtissage'},
        ],
        'equipment': ['Four', 'Plat à gratin', 'Mandoline ou couteau'],
        'allergens': ['Lactose'],
        'tips': [
            {'tip_type': 'astuces', 'content': 'Trancher les pommes de terre à la mandoline pour une épaisseur uniforme (3 mm).'},
            {'tip_type': 'astuces', 'content': 'Ne pas rincer les pommes de terre après découpe : l\'amidon aide à lier le gratin.'},
            {'tip_type': 'erreurs', 'content': 'Ne pas mettre trop de fromage : le vrai dauphinois n\'en contient pas !'},
            {'tip_type': 'accompagnements', 'content': 'Rôti de bœuf ou agneau'},
            {'tip_type': 'accords', 'content': 'Blanc de Savoie ou Saint-Joseph'},
        ],
    },
    {
        'name': 'Mousse au Chocolat',
        'description': 'Une mousse au chocolat aérienne et intense, à la texture légère et fondante, avec seulement 3 ingrédients.',
        'cuisine_type': 'Française',
        'occasion': 'Fête',
        'dish_type': 'Dessert',
        'category': 'Pâtisserie',
        'diet': 'Végétarien',
        'ideal_season': 'Toutes saisons',
        'prep_time': 20,
        'cook_time': 5,
        'rest_time': 120,
        'difficulty': 'Facile',
        'servings': 6,
        'estimated_cost': '€',
        'calories_per_serving': 280,
        'proteins': 7,
        'carbs': 22,
        'fats': 18,
        'sugar': 18,
        'fridge_duration': '2 jours',
        'tags': ['dessert', 'chocolat', 'mousse', 'rapide', 'gourmand'],
        'texture': 'Aérien, fondant',
        'aromatic_profile': 'Chocolat intense, légèrement amer',
        'ingredients': [
            {'name': 'chocolat noir', 'quantity': 200, 'unit': 'g', 'quality': '70% de cacao minimum'},
            {'name': 'œuf', 'quantity': 6, 'unit': 'pièce', 'preparation': 'blancs et jaunes séparés'},
            {'name': 'sucre', 'quantity': 40, 'unit': 'g'},
            {'name': 'beurre', 'quantity': 30, 'unit': 'g', 'optional': True},
            {'name': 'sel', 'quantity': 1, 'unit': 'pincée'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Faire fondre le chocolat au bain-marie avec le beurre. Laisser tiédir.', 'duration': 10, 'technique': 'Mijoter'},
            {'step_number': 2, 'description': 'Incorporer les jaunes d\'œufs un à un au chocolat fondu. Ajouter le sucre et mélanger.', 'duration': 3},
            {'step_number': 3, 'description': 'Monter les blancs en neige ferme avec une pincée de sel.', 'duration': 5, 'technique': 'Fouetter'},
            {'step_number': 4, 'description': 'Incorporer délicatement les blancs en neige au mélange chocolaté en trois fois, avec une spatule, en soulevant la masse.', 'duration': 5},
            {'step_number': 5, 'description': 'Répartir dans des verrines et réfrigérer au moins 2 heures.', 'duration': 2},
        ],
        'equipment': ['Saladier', 'Fouet', 'Spatule', 'Casserole (bain-marie)', 'Verrines'],
        'allergens': ['Lactose', 'Œufs'],
        'tips': [
            {'tip_type': 'astuces', 'content': 'Incorporer les blancs en plusieurs fois et avec délicatesse pour conserver l\'effet mousseux.'},
            {'tip_type': 'astuces', 'content': 'Utiliser un chocolat de qualité : c\'est l\'ingrédient principal !'},
            {'tip_type': 'erreurs', 'content': 'Ne pas laisser d\'eau dans le bol des blancs, ils ne monteraient pas.'},
            {'tip_type': 'variantes', 'content': 'Ajouter un trait d\'espresso ou de rhum pour intensifier le goût.'},
            {'tip_type': 'accords', 'content': 'Banyuls ou Porto'},
        ],
    },
]

count = 0
for recipe in recipes:
    try:
        add_recipe(recipe)
        count += 1
        print(f"✓ Ajoutée : {recipe['name']}")
    except Exception as e:
        print(f"✗ Erreur pour {recipe['name']} : {e}")

print(f"\n{count}/{len(recipes)} recettes ajoutées avec succès !")
