import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from database.db_manager import initialize_db, add_recipe

initialize_db()

recipes = [
    # ── PRINTEMPS ──────────────────────────────────────────────────────────
    {
        'name': 'Velouté d\'Asperges',
        'description': 'Soupe onctueuse aux asperges blanches, légère et raffinée.',
        'cuisine_type': 'Française', 'region': 'France', 'dish_type': 'Entrée',
        'category': 'Soupe', 'diet': 'Végétarien', 'ideal_season': 'Printemps',
        'prep_time': 15, 'cook_time': 25, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€€', 'calories_per_serving': 180, 'proteins': 5, 'carbs': 12, 'fats': 12,
        'tags': ['printemps', 'asperge', 'soupe', 'végétarien'],
        'ingredients': [
            {'name': 'asperge blanche', 'quantity': 800, 'unit': 'g', 'preparation': 'pelées, coupées'},
            {'name': 'oignon', 'quantity': 1, 'unit': 'pièce', 'preparation': 'émincé'},
            {'name': 'pomme de terre', 'quantity': 200, 'unit': 'g', 'preparation': 'en dés'},
            {'name': 'crème fraîche', 'quantity': 10, 'unit': 'cl'},
            {'name': 'beurre', 'quantity': 30, 'unit': 'g'},
            {'name': 'bouillon de légumes', 'quantity': 1, 'unit': 'l'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Faire revenir l\'oignon dans le beurre 3 min.', 'duration': 3},
            {'step_number': 2, 'description': 'Ajouter les asperges, la pomme de terre et le bouillon. Cuire 20 min.', 'duration': 20},
            {'step_number': 3, 'description': 'Mixer, ajouter la crème, saler et poivrer.', 'duration': 3},
        ],
        'allergens': ['Lactose'], 'equipment': ['Casserole', 'Mixeur'],
        'tips': [{'tip_type': 'astuces', 'content': 'Garder les pointes d\'asperges entières pour la décoration.'}],
    },
    {
        'name': 'Salade de Fraises et Roquette',
        'description': 'Salade printanière aux fraises fraîches, roquette et balsamique.',
        'cuisine_type': 'Française', 'dish_type': 'Entrée', 'category': 'Salade',
        'diet': 'Végétarien', 'ideal_season': 'Printemps',
        'prep_time': 10, 'cook_time': 0, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€€', 'calories_per_serving': 120, 'proteins': 3, 'carbs': 14, 'fats': 6,
        'tags': ['printemps', 'fraise', 'salade', 'rapide', 'végétarien'],
        'ingredients': [
            {'name': 'fraise', 'quantity': 400, 'unit': 'g', 'preparation': 'équeutées, coupées en deux'},
            {'name': 'roquette', 'quantity': 100, 'unit': 'g'},
            {'name': 'parmesan', 'quantity': 50, 'unit': 'g', 'preparation': 'en copeaux'},
            {'name': 'vinaigre balsamique', 'quantity': 2, 'unit': 'cuillère à soupe'},
            {'name': 'huile d\'olive', 'quantity': 3, 'unit': 'cuillère à soupe'},
            {'name': 'miel', 'quantity': 1, 'unit': 'cuillère à café'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Préparer la vinaigrette : mélanger huile, vinaigre balsamique et miel.', 'duration': 3},
            {'step_number': 2, 'description': 'Dresser la roquette, disposer les fraises et les copeaux de parmesan. Arroser de vinaigrette.', 'duration': 5},
        ],
        'allergens': ['Lactose'], 'equipment': ['Saladier'],
        'tips': [{'tip_type': 'astuces', 'content': 'Ajouter quelques pignons de pin grillés pour le croquant.'}],
    },
    {
        'name': 'Omelette aux Herbes Fraîches',
        'description': 'Omelette moelleuse garnie de fines herbes du jardin.',
        'cuisine_type': 'Française', 'dish_type': 'Plat principal', 'category': 'Autre',
        'diet': 'Végétarien', 'ideal_season': 'Printemps',
        'prep_time': 5, 'cook_time': 5, 'difficulty': 'Facile', 'servings': 2,
        'estimated_cost': '€', 'calories_per_serving': 220, 'proteins': 16, 'carbs': 2, 'fats': 16,
        'tags': ['printemps', 'œufs', 'rapide', 'herbes'],
        'ingredients': [
            {'name': 'œuf', 'quantity': 4, 'unit': 'pièce'},
            {'name': 'persil', 'quantity': 1, 'unit': 'botte', 'preparation': 'ciselé'},
            {'name': 'ciboulette', 'quantity': 1, 'unit': 'botte', 'preparation': 'ciselée'},
            {'name': 'estragon', 'quantity': 4, 'unit': 'branche', 'preparation': 'ciselé'},
            {'name': 'beurre', 'quantity': 20, 'unit': 'g'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Battre les œufs avec les herbes, sel et poivre.', 'duration': 2},
            {'step_number': 2, 'description': 'Faire fondre le beurre à feu vif, verser les œufs. Cuire 2-3 min en remuant doucement, rouler l\'omelette.', 'duration': 3, 'technique': 'Saisir'},
        ],
        'allergens': ['Œufs', 'Lactose'], 'equipment': ['Poêle'],
        'tips': [{'tip_type': 'astuces', 'content': 'L\'omelette doit rester baveuse au centre.'}],
    },
    {
        'name': 'Risotto aux Petits Pois et Menthe',
        'description': 'Risotto crémeux aux petits pois frais et menthe, parfait au printemps.',
        'cuisine_type': 'Italienne', 'dish_type': 'Plat principal', 'category': 'Riz',
        'diet': 'Végétarien', 'ideal_season': 'Printemps',
        'prep_time': 10, 'cook_time': 25, 'difficulty': 'Intermédiaire', 'servings': 4,
        'estimated_cost': '€€', 'calories_per_serving': 380, 'proteins': 12, 'carbs': 58, 'fats': 12,
        'tags': ['printemps', 'petits pois', 'risotto', 'végétarien', 'italien'],
        'ingredients': [
            {'name': 'riz arborio', 'quantity': 320, 'unit': 'g'},
            {'name': 'petits pois', 'quantity': 300, 'unit': 'g'},
            {'name': 'oignon', 'quantity': 1, 'unit': 'pièce', 'preparation': 'émincé'},
            {'name': 'vin blanc', 'quantity': 15, 'unit': 'cl'},
            {'name': 'bouillon de légumes', 'quantity': 1.2, 'unit': 'l', 'preparation': 'chaud'},
            {'name': 'parmesan', 'quantity': 80, 'unit': 'g', 'preparation': 'râpé'},
            {'name': 'beurre', 'quantity': 40, 'unit': 'g'},
            {'name': 'menthe fraîche', 'quantity': 10, 'unit': 'feuille'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Faire revenir l\'oignon dans le beurre. Ajouter le riz, nacrer 2 min.', 'duration': 4},
            {'step_number': 2, 'description': 'Déglacer au vin blanc. Ajouter le bouillon chaud louche par louche en remuant constamment.', 'duration': 18, 'technique': 'Mijoter'},
            {'step_number': 3, 'description': 'Ajouter les petits pois 5 min avant la fin. Mantecatura : incorporer beurre et parmesan. Garnir de menthe.', 'duration': 5},
        ],
        'allergens': ['Lactose'], 'equipment': ['Casserole', 'Louche'],
        'tips': [{'tip_type': 'astuces', 'content': 'Le bouillon doit être toujours chaud pour ne pas choquer le riz.'}],
    },
    {
        'name': 'Tarte aux Fraises',
        'description': 'Tarte pâtissière aux fraises fraîches sur crème pâtissière vanillée.',
        'cuisine_type': 'Française', 'dish_type': 'Dessert', 'category': 'Pâtisserie',
        'diet': 'Végétarien', 'ideal_season': 'Printemps',
        'prep_time': 30, 'cook_time': 20, 'rest_time': 60, 'difficulty': 'Intermédiaire', 'servings': 8,
        'estimated_cost': '€€', 'calories_per_serving': 310, 'proteins': 7, 'carbs': 42, 'fats': 13,
        'tags': ['printemps', 'fraise', 'tarte', 'pâtisserie', 'dessert'],
        'ingredients': [
            {'name': 'pâte sablée', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'fraise', 'quantity': 600, 'unit': 'g'},
            {'name': 'lait', 'quantity': 50, 'unit': 'cl'},
            {'name': 'œuf', 'quantity': 3, 'unit': 'pièce'},
            {'name': 'sucre', 'quantity': 80, 'unit': 'g'},
            {'name': 'farine', 'quantity': 40, 'unit': 'g'},
            {'name': 'vanille', 'quantity': 1, 'unit': 'gousse'},
            {'name': 'nappage', 'quantity': 1, 'unit': 'sachet', 'optional': True},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Cuire la pâte à blanc 20 min à 180°C.', 'duration': 20, 'temperature': 180},
            {'step_number': 2, 'description': 'Préparer la crème pâtissière : chauffer lait + vanille, blanchir œufs + sucre + farine, verser le lait chaud, épaissir à feu doux.', 'duration': 15},
            {'step_number': 3, 'description': 'Étaler la crème froide sur le fond de tarte, disposer les fraises harmonieusement. Napper.', 'duration': 10},
        ],
        'allergens': ['Gluten', 'Lactose', 'Œufs'], 'equipment': ['Four', 'Moule à tarte', 'Casserole'],
        'tips': [{'tip_type': 'astuces', 'content': 'Choisir des fraises de taille similaire pour un beau rendu.'}],
    },

    # ── ÉTÉ ────────────────────────────────────────────────────────────────
    {
        'name': 'Gazpacho Andalou',
        'description': 'Soupe froide espagnole aux tomates, concombre et poivron, fraîche et désaltérante.',
        'cuisine_type': 'Espagnole', 'region': 'Andalousie', 'dish_type': 'Entrée',
        'category': 'Soupe', 'diet': 'Vegan', 'ideal_season': 'Été',
        'prep_time': 15, 'cook_time': 0, 'rest_time': 120, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€', 'calories_per_serving': 130, 'proteins': 3, 'carbs': 16, 'fats': 7,
        'tags': ['été', 'soupe froide', 'vegan', 'espagnol', 'tomate', 'sans gluten'],
        'ingredients': [
            {'name': 'tomate', 'quantity': 800, 'unit': 'g', 'quality': 'bien mûres'},
            {'name': 'concombre', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'poivron rouge', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'ail', 'quantity': 1, 'unit': 'gousse'},
            {'name': 'huile d\'olive', 'quantity': 4, 'unit': 'cuillère à soupe'},
            {'name': 'vinaigre de xérès', 'quantity': 2, 'unit': 'cuillère à soupe'},
            {'name': 'pain rassis', 'quantity': 50, 'unit': 'g', 'optional': True},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Mixer tous les légumes avec l\'ail, l\'huile et le vinaigre jusqu\'à obtenir un mélange lisse.', 'duration': 5},
            {'step_number': 2, 'description': 'Passer au tamis, assaisonner. Réfrigérer au moins 2h.', 'duration': 5},
        ],
        'allergens': [], 'equipment': ['Mixeur', 'Tamis'],
        'tips': [{'tip_type': 'astuces', 'content': 'Servir avec des dés de concombre, tomate et croûtons en garniture.'}],
    },
    {
        'name': 'Tian Provençal',
        'description': 'Gratin de légumes d\'été en fines tranches, cuit au four avec herbes et huile d\'olive.',
        'cuisine_type': 'Française', 'region': 'Provence', 'dish_type': 'Plat principal',
        'category': 'Grillades', 'diet': 'Vegan', 'ideal_season': 'Été',
        'prep_time': 20, 'cook_time': 60, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€', 'calories_per_serving': 160, 'proteins': 4, 'carbs': 18, 'fats': 8,
        'tags': ['été', 'légumes', 'vegan', 'provençal', 'gratin'],
        'ingredients': [
            {'name': 'courgette', 'quantity': 3, 'unit': 'pièce', 'preparation': 'en rondelles fines'},
            {'name': 'tomate', 'quantity': 4, 'unit': 'pièce', 'preparation': 'en rondelles'},
            {'name': 'aubergine', 'quantity': 1, 'unit': 'pièce', 'preparation': 'en rondelles fines'},
            {'name': 'oignon', 'quantity': 2, 'unit': 'pièce', 'preparation': 'émincé'},
            {'name': 'ail', 'quantity': 3, 'unit': 'gousse'},
            {'name': 'huile d\'olive', 'quantity': 5, 'unit': 'cuillère à soupe'},
            {'name': 'thym', 'quantity': 3, 'unit': 'branche'},
            {'name': 'romarin', 'quantity': 2, 'unit': 'branche'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Préchauffer le four à 180°C. Faire revenir les oignons et l\'ail 5 min à l\'huile d\'olive.', 'duration': 5, 'temperature': 180},
            {'step_number': 2, 'description': 'Étaler les oignons dans un plat à gratin. Disposer les légumes en rondelles en les faisant se chevaucher alternativement.', 'duration': 10},
            {'step_number': 3, 'description': 'Arroser d\'huile, disposer les herbes. Cuire 1h au four.', 'duration': 60, 'temperature': 180},
        ],
        'allergens': [], 'equipment': ['Four', 'Plat à gratin', 'Mandoline'],
        'tips': [{'tip_type': 'astuces', 'content': 'Couper les légumes à la mandoline pour une épaisseur uniforme de 3 mm.'}],
    },
    {
        'name': 'Brochettes de Poulet Mariné',
        'description': 'Brochettes de poulet marinées au citron, ail et herbes, grillées au barbecue.',
        'cuisine_type': 'Française', 'dish_type': 'Plat principal', 'category': 'Grillades',
        'diet': 'Standard', 'ideal_season': 'Été',
        'prep_time': 15, 'cook_time': 15, 'rest_time': 60, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€€', 'calories_per_serving': 280, 'proteins': 38, 'carbs': 3, 'fats': 12,
        'tags': ['été', 'poulet', 'barbecue', 'grillé', 'sans gluten'],
        'ingredients': [
            {'name': 'blanc de poulet', 'quantity': 800, 'unit': 'g', 'preparation': 'en cubes'},
            {'name': 'citron', 'quantity': 2, 'unit': 'pièce', 'preparation': 'jus'},
            {'name': 'ail', 'quantity': 3, 'unit': 'gousse', 'preparation': 'haché'},
            {'name': 'huile d\'olive', 'quantity': 4, 'unit': 'cuillère à soupe'},
            {'name': 'paprika', 'quantity': 1, 'unit': 'cuillère à café'},
            {'name': 'thym', 'quantity': 2, 'unit': 'branche'},
            {'name': 'poivron', 'quantity': 2, 'unit': 'pièce', 'preparation': 'en morceaux'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Mélanger huile, citron, ail, paprika et thym. Mariner le poulet 1h au frais.', 'duration': 60},
            {'step_number': 2, 'description': 'Embrocher poulet et poivrons alternativement. Griller 15 min en retournant à mi-cuisson.', 'duration': 15, 'technique': 'Grillade'},
        ],
        'allergens': [], 'equipment': ['Barbecue ou gril', 'Brochettes'],
        'tips': [{'tip_type': 'accompagnements', 'content': 'Taboulé ou salade verte'}, {'tip_type': 'accords', 'content': 'Rosé bien frais'}],
    },
    {
        'name': 'Courgettes Farcies',
        'description': 'Courgettes garnies d\'une farce à la viande et aux herbes, gratinées au four.',
        'cuisine_type': 'Française', 'dish_type': 'Plat principal', 'category': 'Grillades',
        'diet': 'Standard', 'ideal_season': 'Été',
        'prep_time': 20, 'cook_time': 35, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€€', 'calories_per_serving': 320, 'proteins': 22, 'carbs': 14, 'fats': 18,
        'tags': ['été', 'courgette', 'farci', 'gratinée'],
        'ingredients': [
            {'name': 'courgette', 'quantity': 4, 'unit': 'pièce', 'quality': 'grosses courgettes'},
            {'name': 'viande hachée', 'quantity': 400, 'unit': 'g'},
            {'name': 'oignon', 'quantity': 1, 'unit': 'pièce', 'preparation': 'émincé'},
            {'name': 'tomate', 'quantity': 2, 'unit': 'pièce', 'preparation': 'en dés'},
            {'name': 'ail', 'quantity': 2, 'unit': 'gousse'},
            {'name': 'gruyère râpé', 'quantity': 80, 'unit': 'g'},
            {'name': 'herbes de Provence', 'quantity': 1, 'unit': 'cuillère à café'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Couper les courgettes en deux, évider la chair. Préchauffer le four à 200°C.', 'duration': 10},
            {'step_number': 2, 'description': 'Faire revenir oignon, ail, viande et chair des courgettes. Ajouter les tomates et herbes.', 'duration': 10, 'technique': 'Saisir'},
            {'step_number': 3, 'description': 'Farcir les courgettes, couvrir de gruyère. Enfourner 25 min.', 'duration': 25, 'temperature': 200},
        ],
        'allergens': ['Lactose'], 'equipment': ['Four', 'Poêle', 'Plat à gratin'],
        'tips': [],
    },
    {
        'name': 'Salade de Pastèque Feta Menthe',
        'description': 'Salade rafraîchissante à la pastèque, feta crémeuse et menthe fraîche.',
        'cuisine_type': 'Grecque', 'dish_type': 'Entrée', 'category': 'Salade',
        'diet': 'Végétarien', 'ideal_season': 'Été',
        'prep_time': 10, 'cook_time': 0, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€€', 'calories_per_serving': 160, 'proteins': 5, 'carbs': 22, 'fats': 7,
        'tags': ['été', 'pastèque', 'feta', 'fraîche', 'rapide', 'végétarien'],
        'ingredients': [
            {'name': 'pastèque', 'quantity': 1.2, 'unit': 'kg', 'preparation': 'sans pépins, en cubes'},
            {'name': 'feta', 'quantity': 150, 'unit': 'g', 'preparation': 'émiettée'},
            {'name': 'menthe fraîche', 'quantity': 15, 'unit': 'feuille'},
            {'name': 'huile d\'olive', 'quantity': 2, 'unit': 'cuillère à soupe'},
            {'name': 'citron vert', 'quantity': 1, 'unit': 'pièce', 'preparation': 'jus'},
            {'name': 'olive noire', 'quantity': 50, 'unit': 'g', 'optional': True},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Disposer la pastèque dans un plat. Répartir la feta et les olives. Arroser d\'huile et de jus de citron. Garnir de menthe.', 'duration': 10},
        ],
        'allergens': ['Lactose'], 'equipment': ['Saladier'],
        'tips': [{'tip_type': 'astuces', 'content': 'Servir bien froid, idéal sorti du réfrigérateur.'}],
    },
    {
        'name': 'Pêches Rôties au Miel',
        'description': 'Pêches rôties au four avec miel, amandes effilées et une pointe de cannelle.',
        'cuisine_type': 'Française', 'dish_type': 'Dessert', 'category': 'Pâtisserie',
        'diet': 'Végétarien', 'ideal_season': 'Été',
        'prep_time': 10, 'cook_time': 20, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€', 'calories_per_serving': 190, 'proteins': 3, 'carbs': 32, 'fats': 6,
        'tags': ['été', 'pêche', 'dessert', 'rapide', 'miel'],
        'ingredients': [
            {'name': 'pêche', 'quantity': 6, 'unit': 'pièce', 'preparation': 'coupées en deux, dénoyautées'},
            {'name': 'miel', 'quantity': 3, 'unit': 'cuillère à soupe'},
            {'name': 'beurre', 'quantity': 20, 'unit': 'g'},
            {'name': 'amande effilée', 'quantity': 40, 'unit': 'g'},
            {'name': 'cannelle', 'quantity': 1, 'unit': 'cuillère à café'},
            {'name': 'vanille', 'quantity': 1, 'unit': 'gousse'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Préchauffer le four à 190°C. Poser les pêches dans un plat, face coupée vers le haut.', 'duration': 3, 'temperature': 190},
            {'step_number': 2, 'description': 'Déposer une noisette de beurre, un filet de miel et une pincée de cannelle sur chaque demi-pêche. Parsemer d\'amandes.', 'duration': 5},
            {'step_number': 3, 'description': 'Cuire 20 min jusqu\'à caramélisation. Servir tiède avec une boule de glace vanille.', 'duration': 20, 'temperature': 190},
        ],
        'allergens': ['Lactose', 'Fruits à coque'], 'equipment': ['Four', 'Plat à gratin'],
        'tips': [],
    },
    {
        'name': 'Taboulé Oriental',
        'description': 'Taboulé libanais à la semoule fine, persil, menthe, tomate et citron.',
        'cuisine_type': 'Libanaise', 'dish_type': 'Plat principal', 'category': 'Salade',
        'diet': 'Vegan', 'ideal_season': 'Été',
        'prep_time': 20, 'cook_time': 5, 'rest_time': 30, 'difficulty': 'Facile', 'servings': 6,
        'estimated_cost': '€', 'calories_per_serving': 210, 'proteins': 6, 'carbs': 35, 'fats': 8,
        'tags': ['été', 'taboulé', 'libanais', 'frais', 'vegan', 'semoule'],
        'ingredients': [
            {'name': 'semoule fine', 'quantity': 200, 'unit': 'g'},
            {'name': 'tomate', 'quantity': 4, 'unit': 'pièce', 'preparation': 'en petits dés'},
            {'name': 'persil', 'quantity': 2, 'unit': 'botte', 'preparation': 'finement haché'},
            {'name': 'menthe fraîche', 'quantity': 1, 'unit': 'botte', 'preparation': 'hachée'},
            {'name': 'oignon nouveau', 'quantity': 4, 'unit': 'pièce', 'preparation': 'émincé'},
            {'name': 'citron', 'quantity': 2, 'unit': 'pièce', 'preparation': 'jus'},
            {'name': 'huile d\'olive', 'quantity': 5, 'unit': 'cuillère à soupe'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Réhydrater la semoule avec de l\'eau bouillante salée. Laisser gonfler 5 min, égrener à la fourchette.', 'duration': 10},
            {'step_number': 2, 'description': 'Mélanger tous les ingrédients, assaisonner généreusement de jus de citron, huile, sel et poivre. Réfrigérer 30 min.', 'duration': 5},
        ],
        'allergens': ['Gluten'], 'equipment': ['Saladier'],
        'tips': [{'tip_type': 'astuces', 'content': 'Le persil doit être très finement haché, c\'est lui qui donne le caractère du taboulé.'}],
    },
    {
        'name': 'Glace Maison à la Framboise',
        'description': 'Glace artisanale à la framboise, onctueuse et parfumée, sans sorbetière.',
        'cuisine_type': 'Française', 'dish_type': 'Dessert', 'category': 'Pâtisserie',
        'diet': 'Végétarien', 'ideal_season': 'Été',
        'prep_time': 15, 'cook_time': 0, 'rest_time': 240, 'difficulty': 'Facile', 'servings': 6,
        'estimated_cost': '€€', 'calories_per_serving': 220, 'proteins': 4, 'carbs': 28, 'fats': 11,
        'tags': ['été', 'framboise', 'glace', 'dessert', 'frais'],
        'ingredients': [
            {'name': 'framboise', 'quantity': 400, 'unit': 'g'},
            {'name': 'crème liquide entière', 'quantity': 30, 'unit': 'cl'},
            {'name': 'sucre glace', 'quantity': 100, 'unit': 'g'},
            {'name': 'jus de citron', 'quantity': 1, 'unit': 'cuillère à soupe'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Mixer les framboises avec le sucre glace et le citron. Passer au tamis pour enlever les pépins.', 'duration': 10},
            {'step_number': 2, 'description': 'Monter la crème en chantilly ferme. Incorporer délicatement le coulis de framboise.', 'duration': 8, 'technique': 'Fouetter'},
            {'step_number': 3, 'description': 'Verser dans un bac, filmer et congeler 4h minimum. Remuer toutes les heures les 2 premières heures.', 'duration': 240},
        ],
        'allergens': ['Lactose'], 'equipment': ['Mixeur', 'Fouet', 'Bac congélation'],
        'tips': [{'tip_type': 'astuces', 'content': 'Sortir 10 min avant de servir pour assouplir.'}],
    },
    {
        'name': 'Pizza Margherita',
        'description': 'La pizza classique napolitaine avec sauce tomate, mozzarella et basilic frais.',
        'cuisine_type': 'Italienne', 'region': 'Naples', 'dish_type': 'Plat principal',
        'category': 'Pizza', 'diet': 'Végétarien', 'ideal_season': 'Été',
        'prep_time': 30, 'cook_time': 15, 'rest_time': 60, 'difficulty': 'Intermédiaire', 'servings': 4,
        'estimated_cost': '€', 'calories_per_serving': 380, 'proteins': 15, 'carbs': 52, 'fats': 13,
        'tags': ['été', 'pizza', 'italien', 'tomate', 'végétarien'],
        'ingredients': [
            {'name': 'farine type 00', 'quantity': 500, 'unit': 'g'},
            {'name': 'levure boulangère', 'quantity': 7, 'unit': 'g'},
            {'name': 'eau tiède', 'quantity': 32, 'unit': 'cl'},
            {'name': 'huile d\'olive', 'quantity': 2, 'unit': 'cuillère à soupe'},
            {'name': 'tomate concassée', 'quantity': 400, 'unit': 'g'},
            {'name': 'mozzarella', 'quantity': 250, 'unit': 'g'},
            {'name': 'basilic frais', 'quantity': 10, 'unit': 'feuille'},
            {'name': 'ail', 'quantity': 1, 'unit': 'gousse'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Pétrir la pâte (farine, levure, eau, sel, huile) 10 min. Laisser lever 1h.', 'duration': 70, 'technique': 'Pétrir'},
            {'step_number': 2, 'description': 'Assaisonner les tomates avec ail et sel. Étaler la pâte finement.', 'duration': 10},
            {'step_number': 3, 'description': 'Garnir de sauce tomate, mozzarella déchirée. Cuire 12-15 min au four préchauffé au maximum (250°C+). Ajouter le basilic à la sortie.', 'duration': 15, 'temperature': 250},
        ],
        'allergens': ['Gluten', 'Lactose'], 'equipment': ['Four', 'Pierre à pizza ou plaque'],
        'tips': [{'tip_type': 'astuces', 'content': 'Four au maximum, la cuisson doit être courte et vive.'}],
    },

    # ── AUTOMNE ────────────────────────────────────────────────────────────
    {
        'name': 'Velouté de Potimarron',
        'description': 'Soupe veloutée au potimarron rôti, gingembre et crème de coco.',
        'cuisine_type': 'Française', 'dish_type': 'Entrée', 'category': 'Soupe',
        'diet': 'Vegan', 'ideal_season': 'Automne',
        'prep_time': 15, 'cook_time': 40, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€', 'calories_per_serving': 190, 'proteins': 3, 'carbs': 26, 'fats': 9,
        'tags': ['automne', 'potimarron', 'soupe', 'vegan', 'gingembre'],
        'ingredients': [
            {'name': 'potimarron', 'quantity': 1, 'unit': 'kg', 'preparation': 'épluché, en cubes'},
            {'name': 'oignon', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'gingembre frais', 'quantity': 20, 'unit': 'g', 'preparation': 'râpé'},
            {'name': 'lait de coco', 'quantity': 20, 'unit': 'cl'},
            {'name': 'bouillon de légumes', 'quantity': 80, 'unit': 'cl'},
            {'name': 'huile de coco', 'quantity': 1, 'unit': 'cuillère à soupe'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Rôtir les cubes de potimarron huilés au four 25 min à 200°C.', 'duration': 25, 'temperature': 200},
            {'step_number': 2, 'description': 'Faire revenir oignon et gingembre, ajouter le potimarron rôti et le bouillon. Cuire 10 min.', 'duration': 10},
            {'step_number': 3, 'description': 'Mixer avec le lait de coco, ajuster l\'assaisonnement.', 'duration': 3},
        ],
        'allergens': [], 'equipment': ['Four', 'Casserole', 'Mixeur'],
        'tips': [{'tip_type': 'astuces', 'content': 'Garder la peau du potimarron, elle se mange et donne une belle couleur.'}],
    },
    {
        'name': 'Tarte Tatin aux Poires',
        'description': 'Tarte renversée aux poires caramélisées sur pâte feuilletée croustillante.',
        'cuisine_type': 'Française', 'dish_type': 'Dessert', 'category': 'Pâtisserie',
        'diet': 'Végétarien', 'ideal_season': 'Automne',
        'prep_time': 20, 'cook_time': 40, 'difficulty': 'Intermédiaire', 'servings': 6,
        'estimated_cost': '€€', 'calories_per_serving': 290, 'proteins': 3, 'carbs': 44, 'fats': 12,
        'tags': ['automne', 'poire', 'tarte', 'caramel', 'dessert'],
        'ingredients': [
            {'name': 'poire', 'quantity': 6, 'unit': 'pièce', 'preparation': 'pelées, coupées en deux', 'quality': 'William ou Conférence'},
            {'name': 'sucre', 'quantity': 120, 'unit': 'g'},
            {'name': 'beurre', 'quantity': 60, 'unit': 'g'},
            {'name': 'pâte feuilletée', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'vanille', 'quantity': 1, 'unit': 'gousse'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Faire un caramel brun avec sucre et beurre dans un moule à tatin. Ajouter la vanille.', 'duration': 8},
            {'step_number': 2, 'description': 'Disposer les poires dans le caramel chaud. Couvrir de pâte feuilletée en rentrant les bords.', 'duration': 5},
            {'step_number': 3, 'description': 'Cuire 35-40 min à 180°C. Retourner chaud.', 'duration': 40, 'temperature': 180},
        ],
        'allergens': ['Gluten', 'Lactose'], 'equipment': ['Four', 'Moule à tatin'],
        'tips': [],
    },
    {
        'name': 'Tajine de Poulet aux Pruneaux',
        'description': 'Tajine traditionnel marocain au poulet, pruneaux, amandes et épices orientales.',
        'cuisine_type': 'Marocaine', 'dish_type': 'Plat principal', 'category': 'Ragoût',
        'diet': 'Standard', 'ideal_season': 'Automne',
        'prep_time': 20, 'cook_time': 75, 'difficulty': 'Intermédiaire', 'servings': 4,
        'estimated_cost': '€€', 'calories_per_serving': 460, 'proteins': 36, 'carbs': 38, 'fats': 18,
        'tags': ['automne', 'poulet', 'marocain', 'tajine', 'pruneaux', 'épices'],
        'ingredients': [
            {'name': 'poulet', 'quantity': 1.2, 'unit': 'kg', 'preparation': 'en morceaux'},
            {'name': 'pruneaux', 'quantity': 200, 'unit': 'g'},
            {'name': 'oignon', 'quantity': 2, 'unit': 'pièce', 'preparation': 'émincé'},
            {'name': 'amande effilée', 'quantity': 60, 'unit': 'g'},
            {'name': 'cannelle', 'quantity': 1, 'unit': 'cuillère à café'},
            {'name': 'gingembre', 'quantity': 1, 'unit': 'cuillère à café'},
            {'name': 'curcuma', 'quantity': 0.5, 'unit': 'cuillère à café'},
            {'name': 'miel', 'quantity': 2, 'unit': 'cuillère à soupe'},
            {'name': 'huile d\'olive', 'quantity': 3, 'unit': 'cuillère à soupe'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Faire dorer les morceaux de poulet à l\'huile. Réserver.', 'duration': 10, 'technique': 'Saisir'},
            {'step_number': 2, 'description': 'Faire revenir les oignons avec les épices. Remettre le poulet, couvrir d\'eau à mi-hauteur. Mijoter 45 min.', 'duration': 45, 'technique': 'Mijoter'},
            {'step_number': 3, 'description': 'Ajouter les pruneaux et le miel. Cuire encore 20 min. Garnir d\'amandes grillées.', 'duration': 20},
        ],
        'allergens': ['Fruits à coque'], 'equipment': ['Tajine ou cocotte'],
        'tips': [{'tip_type': 'accompagnements', 'content': 'Semoule de couscous'}, {'tip_type': 'accords', 'content': 'Thé à la menthe'}],
    },
    {
        'name': 'Gratin de Butternut',
        'description': 'Gratin fondant à la courge butternut, gruyère et noix muscade.',
        'cuisine_type': 'Française', 'dish_type': 'Plat principal', 'category': 'Grillades',
        'diet': 'Végétarien', 'ideal_season': 'Automne',
        'prep_time': 20, 'cook_time': 45, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€', 'calories_per_serving': 290, 'proteins': 9, 'carbs': 30, 'fats': 16,
        'tags': ['automne', 'butternut', 'gratin', 'végétarien', 'réconfort'],
        'ingredients': [
            {'name': 'butternut', 'quantity': 1, 'unit': 'kg', 'preparation': 'épluchée, en tranches'},
            {'name': 'crème fraîche', 'quantity': 20, 'unit': 'cl'},
            {'name': 'gruyère râpé', 'quantity': 120, 'unit': 'g'},
            {'name': 'ail', 'quantity': 2, 'unit': 'gousse'},
            {'name': 'muscade', 'quantity': 1, 'unit': 'pincée'},
            {'name': 'beurre', 'quantity': 15, 'unit': 'g'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Précuire les tranches de butternut à la vapeur 10 min.', 'duration': 10, 'technique': 'Vapeur'},
            {'step_number': 2, 'description': 'Beurrer un plat à gratin. Disposer les tranches en couches, napper de crème à l\'ail, muscade, sel et poivre. Couvrir de gruyère.', 'duration': 10},
            {'step_number': 3, 'description': 'Cuire 35 min à 190°C jusqu\'à gratinage doré.', 'duration': 35, 'temperature': 190},
        ],
        'allergens': ['Lactose'], 'equipment': ['Four', 'Plat à gratin'],
        'tips': [],
    },
    {
        'name': 'Tarte aux Figues et Fromage de Chèvre',
        'description': 'Tarte salée aux figues fraîches et fromage de chèvre sur pâte sablée aux herbes.',
        'cuisine_type': 'Française', 'dish_type': 'Entrée', 'category': 'Tarte',
        'diet': 'Végétarien', 'ideal_season': 'Automne',
        'prep_time': 20, 'cook_time': 30, 'difficulty': 'Facile', 'servings': 6,
        'estimated_cost': '€€', 'calories_per_serving': 280, 'proteins': 9, 'carbs': 26, 'fats': 16,
        'tags': ['automne', 'figue', 'chèvre', 'tarte salée'],
        'ingredients': [
            {'name': 'pâte brisée', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'figue', 'quantity': 8, 'unit': 'pièce', 'preparation': 'coupées en quartiers'},
            {'name': 'fromage de chèvre', 'quantity': 150, 'unit': 'g'},
            {'name': 'miel', 'quantity': 2, 'unit': 'cuillère à soupe'},
            {'name': 'thym', 'quantity': 3, 'unit': 'branche'},
            {'name': 'noix', 'quantity': 40, 'unit': 'g', 'optional': True},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Préchauffer le four à 180°C. Foncer le moule de pâte brisée.', 'duration': 5, 'temperature': 180},
            {'step_number': 2, 'description': 'Disposer le fromage de chèvre émietté, les figues et les noix. Arroser de miel, parsemer de thym.', 'duration': 8},
            {'step_number': 3, 'description': 'Cuire 25-30 min jusqu\'à dorure.', 'duration': 30, 'temperature': 180},
        ],
        'allergens': ['Gluten', 'Lactose', 'Fruits à coque'], 'equipment': ['Four', 'Moule à tarte'],
        'tips': [],
    },
    {
        'name': 'Compote de Pommes Maison',
        'description': 'Compote onctueuse de pommes à la cannelle, sans sucre ajouté.',
        'cuisine_type': 'Française', 'dish_type': 'Dessert', 'category': 'Autre',
        'diet': 'Vegan', 'ideal_season': 'Automne',
        'prep_time': 10, 'cook_time': 20, 'difficulty': 'Facile', 'servings': 6,
        'estimated_cost': '€', 'calories_per_serving': 90, 'proteins': 0.5, 'carbs': 22, 'fats': 0.3,
        'tags': ['automne', 'pomme', 'compote', 'sans sucre', 'vegan', 'économique'],
        'ingredients': [
            {'name': 'pomme', 'quantity': 1.2, 'unit': 'kg', 'preparation': 'pelées, épépinées, en morceaux'},
            {'name': 'cannelle', 'quantity': 1, 'unit': 'cuillère à café'},
            {'name': 'jus de citron', 'quantity': 1, 'unit': 'cuillère à soupe'},
            {'name': 'eau', 'quantity': 5, 'unit': 'cuillère à soupe'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Mettre tous les ingrédients dans une casserole. Cuire à feu moyen 20 min en remuant.', 'duration': 20, 'technique': 'Mijoter'},
            {'step_number': 2, 'description': 'Écraser grossièrement à la fourchette ou mixer selon la texture désirée.', 'duration': 3},
        ],
        'allergens': [], 'equipment': ['Casserole'],
        'tips': [{'tip_type': 'variantes', 'content': 'Ajouter poire ou coing pour varier les saveurs.'}],
    },

    # ── HIVER ──────────────────────────────────────────────────────────────
    {
        'name': 'Pot-au-Feu',
        'description': 'Le grand classique de la cuisine hivernale française : bœuf et légumes mijotés dans un bouillon parfumé.',
        'cuisine_type': 'Française', 'dish_type': 'Plat principal', 'category': 'Ragoût',
        'diet': 'Standard', 'ideal_season': 'Hiver',
        'prep_time': 30, 'cook_time': 180, 'difficulty': 'Facile', 'servings': 6,
        'estimated_cost': '€€', 'calories_per_serving': 420, 'proteins': 38, 'carbs': 22, 'fats': 18,
        'tags': ['hiver', 'bœuf', 'légumes', 'mijoté', 'traditionnel', 'réconfort'],
        'ingredients': [
            {'name': 'bœuf à braiser', 'quantity': 1.2, 'unit': 'kg', 'quality': 'paleron, gîte, joue'},
            {'name': 'os à moelle', 'quantity': 4, 'unit': 'pièce'},
            {'name': 'carotte', 'quantity': 4, 'unit': 'pièce'},
            {'name': 'poireau', 'quantity': 2, 'unit': 'pièce'},
            {'name': 'navet', 'quantity': 2, 'unit': 'pièce'},
            {'name': 'céleri', 'quantity': 2, 'unit': 'branche'},
            {'name': 'oignon', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'bouquet garni', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'poivre noir', 'quantity': 10, 'unit': 'pièce'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Mettre la viande dans une grande marmite, couvrir d\'eau froide. Porter à ébullition, écumer soigneusement.', 'duration': 20},
            {'step_number': 2, 'description': 'Ajouter tous les légumes, le bouquet garni et les épices. Cuire 3h à feu très doux.', 'duration': 180, 'technique': 'Mijoter'},
            {'step_number': 3, 'description': 'Servir la viande découpée avec les légumes et le bouillon en entrée.', 'duration': 10},
        ],
        'allergens': [], 'equipment': ['Grande marmite'],
        'tips': [{'tip_type': 'astuces', 'content': 'Le bouillon sert d\'entrée avec du pain grillé et de la moelle.'}, {'tip_type': 'accompagnements', 'content': 'Cornichons, moutarde à l\'ancienne, gros sel'}],
    },
    {
        'name': 'Cassoulet Toulousain',
        'description': 'Le célèbre cassoulet du Languedoc aux haricots blancs, confit de canard, saucisses et lardons.',
        'cuisine_type': 'Française', 'region': 'Languedoc', 'dish_type': 'Plat principal',
        'category': 'Ragoût', 'diet': 'Standard', 'ideal_season': 'Hiver',
        'prep_time': 30, 'cook_time': 180, 'rest_time': 720, 'difficulty': 'Difficile', 'servings': 6,
        'estimated_cost': '€€€', 'calories_per_serving': 680, 'proteins': 42, 'carbs': 48, 'fats': 32,
        'tags': ['hiver', 'cassoulet', 'haricots', 'canard', 'traditionnel', 'réconfort'],
        'ingredients': [
            {'name': 'haricot blanc sec', 'quantity': 500, 'unit': 'g', 'preparation': 'trempés une nuit'},
            {'name': 'confit de canard', 'quantity': 4, 'unit': 'pièce'},
            {'name': 'saucisse de Toulouse', 'quantity': 400, 'unit': 'g'},
            {'name': 'lardon', 'quantity': 150, 'unit': 'g'},
            {'name': 'oignon', 'quantity': 2, 'unit': 'pièce'},
            {'name': 'tomate concassée', 'quantity': 400, 'unit': 'g'},
            {'name': 'ail', 'quantity': 4, 'unit': 'gousse'},
            {'name': 'bouquet garni', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'chapelure', 'quantity': 50, 'unit': 'g'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Cuire les haricots égouttés 1h dans un bouillon avec le bouquet garni.', 'duration': 60},
            {'step_number': 2, 'description': 'Faire revenir lardons, saucisses et oignons. Ajouter tomates et ail.', 'duration': 15, 'technique': 'Saisir'},
            {'step_number': 3, 'description': 'Assembler haricots, viandes et sauce dans une cassole. Couvrir de chapelure. Cuire 2h à 160°C en "cassant" la croûte 3 fois.', 'duration': 120, 'temperature': 160},
        ],
        'allergens': ['Gluten'], 'equipment': ['Cassole ou cocotte', 'Four'],
        'tips': [{'tip_type': 'astuces', 'content': 'Casser la croûte 3 fois minimum pendant la cuisson, c\'est le secret du cassoulet !'}],
    },
    {
        'name': 'Blanquette de Veau',
        'description': 'Veau tendre mijoté dans une sauce blanche crémeuse aux champignons et oignons grelots.',
        'cuisine_type': 'Française', 'dish_type': 'Plat principal', 'category': 'Ragoût',
        'diet': 'Standard', 'ideal_season': 'Hiver',
        'prep_time': 25, 'cook_time': 90, 'difficulty': 'Intermédiaire', 'servings': 6,
        'estimated_cost': '€€€', 'calories_per_serving': 460, 'proteins': 36, 'carbs': 18, 'fats': 26,
        'tags': ['hiver', 'veau', 'blanquette', 'sauce blanche', 'traditionnel'],
        'ingredients': [
            {'name': 'veau', 'quantity': 1.2, 'unit': 'kg', 'preparation': 'en morceaux', 'quality': 'épaule ou tendron'},
            {'name': 'champignon de Paris', 'quantity': 300, 'unit': 'g'},
            {'name': 'oignon grelot', 'quantity': 200, 'unit': 'g'},
            {'name': 'carotte', 'quantity': 2, 'unit': 'pièce'},
            {'name': 'beurre', 'quantity': 60, 'unit': 'g'},
            {'name': 'farine', 'quantity': 50, 'unit': 'g'},
            {'name': 'crème fraîche', 'quantity': 20, 'unit': 'cl'},
            {'name': 'jaune d\'œuf', 'quantity': 2, 'unit': 'pièce'},
            {'name': 'citron', 'quantity': 1, 'unit': 'pièce', 'preparation': 'jus'},
            {'name': 'bouquet garni', 'quantity': 1, 'unit': 'pièce'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Blanchir le veau : couvrir d\'eau froide, porter à ébullition, rincer. Remettre à cuire avec carottes et bouquet garni 1h30.', 'duration': 90, 'technique': 'Blanchir'},
            {'step_number': 2, 'description': 'Faire un roux blanc (beurre + farine), incorporer le bouillon de cuisson, faire épaissir.', 'duration': 10},
            {'step_number': 3, 'description': 'Lier avec jaunes d\'œufs + crème + jus de citron. Ajouter champignons et oignons grelots cuits. Rectifier l\'assaisonnement.', 'duration': 10},
        ],
        'allergens': ['Gluten', 'Lactose', 'Œufs'], 'equipment': ['Grande casserole', 'Casserole pour sauce'],
        'tips': [{'tip_type': 'astuces', 'content': 'Ne jamais faire bouillir après l\'ajout des jaunes d\'œufs.'}, {'tip_type': 'accompagnements', 'content': 'Riz blanc'}],
    },
    {
        'name': 'Gratin de Chou-Fleur',
        'description': 'Chou-fleur en gratin nappé de sauce béchamel et gratiné au fromage.',
        'cuisine_type': 'Française', 'dish_type': 'Plat principal', 'category': 'Grillades',
        'diet': 'Végétarien', 'ideal_season': 'Hiver',
        'prep_time': 15, 'cook_time': 35, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€', 'calories_per_serving': 280, 'proteins': 13, 'carbs': 18, 'fats': 17,
        'tags': ['hiver', 'chou-fleur', 'gratin', 'béchamel', 'végétarien'],
        'ingredients': [
            {'name': 'chou-fleur', 'quantity': 1, 'unit': 'pièce', 'preparation': 'en bouquets'},
            {'name': 'beurre', 'quantity': 40, 'unit': 'g'},
            {'name': 'farine', 'quantity': 40, 'unit': 'g'},
            {'name': 'lait', 'quantity': 50, 'unit': 'cl'},
            {'name': 'gruyère râpé', 'quantity': 100, 'unit': 'g'},
            {'name': 'muscade', 'quantity': 1, 'unit': 'pincée'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Cuire le chou-fleur à l\'eau bouillante salée 8 min, égoutter.', 'duration': 8},
            {'step_number': 2, 'description': 'Préparer la béchamel : roux beurre-farine, incorporer le lait chaud, remuer jusqu\'à épaississement. Saler, poivrer, muscader.', 'duration': 10},
            {'step_number': 3, 'description': 'Disposer le chou-fleur dans un plat, napper de béchamel, couvrir de gruyère. Gratiner 20 min à 200°C.', 'duration': 20, 'temperature': 200, 'technique': 'Gratiner'},
        ],
        'allergens': ['Gluten', 'Lactose'], 'equipment': ['Casserole', 'Plat à gratin', 'Four'],
        'tips': [],
    },
    {
        'name': 'Fondue Savoyarde',
        'description': 'Fondue au fromage fondu (comté, beaufort, emmental) dans laquelle on trempe des cubes de pain.',
        'cuisine_type': 'Française', 'region': 'Savoie', 'dish_type': 'Plat principal',
        'category': 'Autre', 'diet': 'Végétarien', 'ideal_season': 'Hiver',
        'prep_time': 10, 'cook_time': 15, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€€€', 'calories_per_serving': 680, 'proteins': 38, 'carbs': 28, 'fats': 44,
        'tags': ['hiver', 'fromage', 'convivial', 'savoie', 'végétarien'],
        'ingredients': [
            {'name': 'comté', 'quantity': 300, 'unit': 'g', 'preparation': 'râpé'},
            {'name': 'beaufort', 'quantity': 200, 'unit': 'g', 'preparation': 'râpé'},
            {'name': 'emmental', 'quantity': 200, 'unit': 'g', 'preparation': 'râpé'},
            {'name': 'vin blanc de Savoie', 'quantity': 30, 'unit': 'cl'},
            {'name': 'ail', 'quantity': 1, 'unit': 'gousse'},
            {'name': 'fécule de maïs', 'quantity': 1, 'unit': 'cuillère à soupe'},
            {'name': 'pain de campagne', 'quantity': 400, 'unit': 'g', 'preparation': 'en cubes'},
            {'name': 'kirsch', 'quantity': 2, 'unit': 'cuillère à soupe', 'optional': True},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Frotter le caquelon avec la gousse d\'ail. Verser le vin blanc, chauffer.', 'duration': 3},
            {'step_number': 2, 'description': 'Incorporer les fromages progressivement en remuant en 8. Dissoudre la fécule dans le kirsch et ajouter pour lier.', 'duration': 10},
            {'step_number': 3, 'description': 'Maintenir sur le réchaud à feu doux. Tremper les cubes de pain.', 'duration': 2},
        ],
        'allergens': ['Gluten', 'Lactose'], 'equipment': ['Caquelon à fondue', 'Réchaud', 'Fourchettes à fondue'],
        'tips': [{'tip_type': 'astuces', 'content': 'Si la fondue est trop épaisse, ajouter un peu de vin blanc chaud.'}, {'tip_type': 'accords', 'content': 'Vin blanc de Savoie ou Apremont'}],
    },
    {
        'name': 'Bûche de Noël au Chocolat',
        'description': 'Bûche de Noël traditionnelle garnie de crème au beurre au chocolat sur génoise moelleuse.',
        'cuisine_type': 'Française', 'occasion': 'Noël', 'dish_type': 'Dessert',
        'category': 'Pâtisserie', 'diet': 'Végétarien', 'ideal_season': 'Hiver',
        'prep_time': 60, 'cook_time': 12, 'rest_time': 120, 'difficulty': 'Difficile', 'servings': 8,
        'estimated_cost': '€€', 'calories_per_serving': 480, 'proteins': 8, 'carbs': 52, 'fats': 28,
        'tags': ['hiver', 'noël', 'bûche', 'chocolat', 'fête', 'dessert'],
        'ingredients': [
            {'name': 'œuf', 'quantity': 4, 'unit': 'pièce'},
            {'name': 'sucre', 'quantity': 120, 'unit': 'g'},
            {'name': 'farine', 'quantity': 80, 'unit': 'g'},
            {'name': 'cacao non sucré', 'quantity': 30, 'unit': 'g'},
            {'name': 'beurre', 'quantity': 200, 'unit': 'g', 'preparation': 'ramolli'},
            {'name': 'sucre glace', 'quantity': 150, 'unit': 'g'},
            {'name': 'chocolat noir', 'quantity': 150, 'unit': 'g', 'preparation': 'fondu'},
            {'name': 'rhum', 'quantity': 2, 'unit': 'cuillère à soupe', 'optional': True},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Génoise : battre œufs + sucre au ruban, incorporer farine + cacao tamisés. Étaler sur plaque, cuire 12 min à 180°C.', 'duration': 20, 'temperature': 180, 'technique': 'Fouetter'},
            {'step_number': 2, 'description': 'Rouler la génoise chaude dans un torchon humide. Laisser refroidir.', 'duration': 30},
            {'step_number': 3, 'description': 'Crème au beurre : battre beurre + sucre glace + chocolat fondu. Dérouler la génoise, garnir, rouler. Décorer avec le reste de crème, strié à la fourchette.', 'duration': 20},
        ],
        'allergens': ['Gluten', 'Lactose', 'Œufs'], 'equipment': ['Four', 'Plaque de cuisson', 'Robot ou fouet'],
        'tips': [{'tip_type': 'astuces', 'content': 'Rouler la génoise encore chaude pour éviter qu\'elle ne se casse.'}],
    },

    # ── TOUTES SAISONS ─────────────────────────────────────────────────────
    {
        'name': 'Pâtes Carbonara',
        'description': 'La vraie carbonara romaine sans crème : œufs, guanciale, pecorino et poivre.',
        'cuisine_type': 'Italienne', 'region': 'Rome', 'dish_type': 'Plat principal',
        'category': 'Pâtes', 'diet': 'Standard', 'ideal_season': 'Toutes saisons',
        'prep_time': 10, 'cook_time': 15, 'difficulty': 'Intermédiaire', 'servings': 4,
        'estimated_cost': '€', 'calories_per_serving': 520, 'proteins': 24, 'carbs': 62, 'fats': 20,
        'tags': ['pâtes', 'italien', 'rapide', 'carbonara', 'économique'],
        'ingredients': [
            {'name': 'spaghetti', 'quantity': 400, 'unit': 'g'},
            {'name': 'guanciale ou lardons', 'quantity': 150, 'unit': 'g'},
            {'name': 'jaune d\'œuf', 'quantity': 4, 'unit': 'pièce'},
            {'name': 'œuf entier', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'pecorino romano', 'quantity': 80, 'unit': 'g', 'preparation': 'râpé', 'replacement': 'parmesan'},
            {'name': 'poivre noir', 'quantity': 1, 'unit': 'cuillère à café', 'preparation': 'concassé grossièrement'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Cuire les pâtes al dente. Faire dorer le guanciale à sec.', 'duration': 12},
            {'step_number': 2, 'description': 'Battre jaunes + œuf entier + pecorino + poivre. Égoutter les pâtes en gardant un verre d\'eau de cuisson.', 'duration': 3},
            {'step_number': 3, 'description': 'Hors du feu, mélanger pâtes chaudes + guanciale + appareil œufs. Ajouter l\'eau de cuisson pour crémer. Servir immédiatement.', 'duration': 2},
        ],
        'allergens': ['Gluten', 'Œufs', 'Lactose'], 'equipment': ['Casserole', 'Poêle', 'Saladier'],
        'tips': [{'tip_type': 'erreurs', 'content': 'Pas de crème fraîche dans la vraie carbonara !'}, {'tip_type': 'astuces', 'content': 'L\'eau de cuisson est la clé de l\'onctuosité.'}],
    },
    {
        'name': 'Œufs Cocotte',
        'description': 'Œufs cuits doucement à la cocotte avec crème et herbes, plat d\'une élégante simplicité.',
        'cuisine_type': 'Française', 'dish_type': 'Entrée', 'category': 'Autre',
        'diet': 'Végétarien', 'ideal_season': 'Toutes saisons',
        'prep_time': 5, 'cook_time': 12, 'difficulty': 'Facile', 'servings': 2,
        'estimated_cost': '€', 'calories_per_serving': 220, 'proteins': 13, 'carbs': 2, 'fats': 18,
        'tags': ['œufs', 'rapide', 'végétarien', 'élégant', 'brunch'],
        'ingredients': [
            {'name': 'œuf', 'quantity': 4, 'unit': 'pièce'},
            {'name': 'crème fraîche', 'quantity': 4, 'unit': 'cuillère à soupe'},
            {'name': 'beurre', 'quantity': 10, 'unit': 'g'},
            {'name': 'ciboulette', 'quantity': 1, 'unit': 'botte'},
            {'name': 'saumon fumé', 'quantity': 2, 'unit': 'tranche', 'optional': True},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Préchauffer le four à 180°C. Beurrer des ramequins, déposer une cuillère de crème.', 'duration': 5, 'temperature': 180},
            {'step_number': 2, 'description': 'Casser délicatement un œuf dans chaque ramequin. Ajouter la crème restante, assaisonner.', 'duration': 2},
            {'step_number': 3, 'description': 'Cuire au bain-marie 10-12 min. Le blanc doit être pris, le jaune coulant.', 'duration': 12, 'technique': 'Vapeur'},
        ],
        'allergens': ['Lactose', 'Œufs'], 'equipment': ['Four', 'Ramequins', 'Plat bain-marie'],
        'tips': [],
    },
    {
        'name': 'Curry de Lentilles (Dahl)',
        'description': 'Curry indien de lentilles corail au lait de coco, tomates et épices parfumées.',
        'cuisine_type': 'Indienne', 'dish_type': 'Plat principal', 'category': 'Ragoût',
        'diet': 'Vegan', 'ideal_season': 'Toutes saisons',
        'prep_time': 10, 'cook_time': 30, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€', 'calories_per_serving': 340, 'proteins': 16, 'carbs': 48, 'fats': 10,
        'tags': ['indien', 'lentilles', 'curry', 'vegan', 'économique', 'protéines'],
        'ingredients': [
            {'name': 'lentille corail', 'quantity': 300, 'unit': 'g'},
            {'name': 'lait de coco', 'quantity': 40, 'unit': 'cl'},
            {'name': 'tomate concassée', 'quantity': 400, 'unit': 'g'},
            {'name': 'oignon', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'ail', 'quantity': 3, 'unit': 'gousse'},
            {'name': 'gingembre', 'quantity': 15, 'unit': 'g'},
            {'name': 'curry en poudre', 'quantity': 2, 'unit': 'cuillère à café'},
            {'name': 'curcuma', 'quantity': 1, 'unit': 'cuillère à café'},
            {'name': 'huile de coco', 'quantity': 2, 'unit': 'cuillère à soupe'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Faire revenir oignon, ail, gingembre avec les épices 3 min.', 'duration': 3, 'technique': 'Saisir'},
            {'step_number': 2, 'description': 'Ajouter tomates, lentilles rincées et lait de coco. Cuire 25 min à feu moyen.', 'duration': 25, 'technique': 'Mijoter'},
        ],
        'allergens': [], 'equipment': ['Casserole'],
        'tips': [{'tip_type': 'accompagnements', 'content': 'Riz basmati, naan'}, {'tip_type': 'astuces', 'content': 'Ajouter des épinards frais en fin de cuisson.'}],
    },
    {
        'name': 'Saumon en Papillote',
        'description': 'Filet de saumon cuit en papillote avec légumes croquants, citron et herbes fraîches.',
        'cuisine_type': 'Française', 'dish_type': 'Plat principal', 'category': 'Autre',
        'diet': 'Sans gluten', 'ideal_season': 'Toutes saisons',
        'prep_time': 10, 'cook_time': 18, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€€€', 'calories_per_serving': 340, 'proteins': 34, 'carbs': 6, 'fats': 20,
        'tags': ['saumon', 'poisson', 'papillote', 'léger', 'sans gluten', 'rapide'],
        'ingredients': [
            {'name': 'filet de saumon', 'quantity': 4, 'unit': 'pièce', 'quality': '150g chacun'},
            {'name': 'citron', 'quantity': 2, 'unit': 'pièce', 'preparation': 'en rondelles'},
            {'name': 'courgette', 'quantity': 2, 'unit': 'pièce', 'preparation': 'en julienne'},
            {'name': 'carotte', 'quantity': 2, 'unit': 'pièce', 'preparation': 'en julienne'},
            {'name': 'aneth', 'quantity': 1, 'unit': 'botte'},
            {'name': 'huile d\'olive', 'quantity': 2, 'unit': 'cuillère à soupe'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Préchauffer le four à 200°C. Sur du papier aluminium, disposer les légumes en julienne, poser le saumon, ajouter citron et aneth. Refermer hermétiquement.', 'duration': 8, 'temperature': 200},
            {'step_number': 2, 'description': 'Cuire 18 min. Ouvrir avec précaution et servir dans la papillote.', 'duration': 18, 'temperature': 200},
        ],
        'allergens': ['Poisson'], 'equipment': ['Four', 'Papier aluminium'],
        'tips': [{'tip_type': 'astuces', 'content': 'Bien fermer les papillotes pour garder la vapeur.'}, {'tip_type': 'accompagnements', 'content': 'Riz basmati ou quinoa'}],
    },
    {
        'name': 'Gâteau au Yaourt',
        'description': 'Le classique gâteau au yaourt, moelleux et rapide à préparer avec le pot comme mesure.',
        'cuisine_type': 'Française', 'dish_type': 'Dessert', 'category': 'Pâtisserie',
        'diet': 'Végétarien', 'ideal_season': 'Toutes saisons',
        'prep_time': 10, 'cook_time': 35, 'difficulty': 'Facile', 'servings': 8,
        'estimated_cost': '€', 'calories_per_serving': 240, 'proteins': 5, 'carbs': 36, 'fats': 9,
        'tags': ['gâteau', 'yaourt', 'moelleux', 'économique', 'enfants', 'rapide'],
        'ingredients': [
            {'name': 'yaourt nature', 'quantity': 1, 'unit': 'pièce', 'quality': '125g — le pot sert de mesure'},
            {'name': 'sucre', 'quantity': 2, 'unit': 'tasse'},
            {'name': 'farine', 'quantity': 3, 'unit': 'tasse'},
            {'name': 'huile', 'quantity': 0.5, 'unit': 'tasse'},
            {'name': 'œuf', 'quantity': 3, 'unit': 'pièce'},
            {'name': 'levure chimique', 'quantity': 1, 'unit': 'sachet'},
            {'name': 'arôme vanille', 'quantity': 1, 'unit': 'cuillère à café'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Préchauffer le four à 180°C. Mélanger yaourt, sucre, œufs, huile et vanille dans un saladier.', 'duration': 5, 'temperature': 180},
            {'step_number': 2, 'description': 'Incorporer la farine et la levure tamisées. Mélanger sans excès.', 'duration': 3},
            {'step_number': 3, 'description': 'Verser dans un moule beurré et fariné. Cuire 35 min.', 'duration': 35, 'temperature': 180},
        ],
        'allergens': ['Gluten', 'Lactose', 'Œufs'], 'equipment': ['Four', 'Moule à gâteau', 'Saladier'],
        'tips': [{'tip_type': 'variantes', 'content': 'Ajouter des pépites de chocolat, des zestes de citron ou des framboises.'}],
    },
    {
        'name': 'Steak Haché Maison',
        'description': 'Steak haché artisanal, juteux et parfumé, façonné et grillé à la poêle.',
        'cuisine_type': 'Française', 'dish_type': 'Plat principal', 'category': 'Grillades',
        'diet': 'Standard', 'ideal_season': 'Toutes saisons',
        'prep_time': 10, 'cook_time': 8, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€€', 'calories_per_serving': 380, 'proteins': 28, 'carbs': 0, 'fats': 28,
        'tags': ['bœuf', 'steak', 'rapide', 'protéines', 'sans gluten'],
        'ingredients': [
            {'name': 'bœuf haché', 'quantity': 600, 'unit': 'g', 'quality': '15-20% matière grasse'},
            {'name': 'échalote', 'quantity': 2, 'unit': 'pièce', 'preparation': 'finement hachée'},
            {'name': 'persil', 'quantity': 3, 'unit': 'branche', 'preparation': 'haché'},
            {'name': 'moutarde', 'quantity': 1, 'unit': 'cuillère à café'},
            {'name': 'beurre', 'quantity': 20, 'unit': 'g'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Mélanger délicatement le bœuf, échalotes, persil, moutarde, sel et poivre. Façonner en steaks sans trop travailler la viande.', 'duration': 5},
            {'step_number': 2, 'description': 'Cuire dans un beurre bien chaud 3-4 min de chaque côté selon la cuisson désirée.', 'duration': 8, 'technique': 'Saisir'},
        ],
        'allergens': [], 'equipment': ['Poêle'],
        'tips': [{'tip_type': 'astuces', 'content': 'Ne pas trop travailler la viande hachée pour garder la tendreté.'}],
    },
    {
        'name': 'Tapenade Maison',
        'description': 'Tapenade provençale aux olives noires, câpres, anchois et huile d\'olive.',
        'cuisine_type': 'Française', 'region': 'Provence', 'dish_type': 'Snack',
        'category': 'Sauce', 'diet': 'Sans gluten', 'ideal_season': 'Toutes saisons',
        'prep_time': 10, 'cook_time': 0, 'difficulty': 'Facile', 'servings': 8,
        'estimated_cost': '€€', 'calories_per_serving': 120, 'proteins': 2, 'carbs': 2, 'fats': 12,
        'tags': ['apéritif', 'olive', 'provençal', 'tartine', 'sans gluten'],
        'ingredients': [
            {'name': 'olive noire', 'quantity': 200, 'unit': 'g', 'preparation': 'dénoyautées'},
            {'name': 'câpre', 'quantity': 2, 'unit': 'cuillère à soupe'},
            {'name': 'anchois', 'quantity': 4, 'unit': 'filet'},
            {'name': 'ail', 'quantity': 1, 'unit': 'gousse'},
            {'name': 'huile d\'olive', 'quantity': 4, 'unit': 'cuillère à soupe'},
            {'name': 'jus de citron', 'quantity': 1, 'unit': 'cuillère à soupe'},
            {'name': 'thym', 'quantity': 1, 'unit': 'branche'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Mixer tous les ingrédients en une pâte grossière. Ajuster l\'huile selon la consistance désirée.', 'duration': 5},
        ],
        'allergens': ['Poisson'], 'equipment': ['Mixeur'],
        'tips': [{'tip_type': 'astuces', 'content': 'Laisser reposer 1h au frais avant de servir pour que les saveurs se mêlent.'}],
    },
    {
        'name': 'Crêpes Bretonnes',
        'description': 'Crêpes fines et dorées, à déguster sucrées ou en galette salée.',
        'cuisine_type': 'Française', 'region': 'Bretagne', 'dish_type': 'Dessert',
        'category': 'Pâtisserie', 'diet': 'Végétarien', 'ideal_season': 'Toutes saisons',
        'prep_time': 10, 'cook_time': 30, 'rest_time': 60, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€', 'calories_per_serving': 280, 'proteins': 9, 'carbs': 38, 'fats': 10,
        'tags': ['crêpes', 'breton', 'dessert', 'économique', 'chandeleur'],
        'ingredients': [
            {'name': 'farine', 'quantity': 250, 'unit': 'g'},
            {'name': 'lait', 'quantity': 50, 'unit': 'cl'},
            {'name': 'œuf', 'quantity': 3, 'unit': 'pièce'},
            {'name': 'beurre fondu', 'quantity': 40, 'unit': 'g'},
            {'name': 'sucre', 'quantity': 1, 'unit': 'cuillère à soupe'},
            {'name': 'sel', 'quantity': 1, 'unit': 'pincée'},
            {'name': 'rhum', 'quantity': 1, 'unit': 'cuillère à soupe', 'optional': True},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Mélanger farine, œufs, sucre et sel. Incorporer le lait progressivement. Ajouter le beurre fondu. Laisser reposer 1h.', 'duration': 10},
            {'step_number': 2, 'description': 'Cuire dans une poêle légèrement huilée, 1 min de chaque côté.', 'duration': 30},
        ],
        'allergens': ['Gluten', 'Lactose', 'Œufs'], 'equipment': ['Poêle à crêpes', 'Spatule'],
        'tips': [{'tip_type': 'variantes', 'content': 'Pour les galettes salées, utiliser de la farine de sarrasin sans sucre.'}, {'tip_type': 'astuces', 'content': 'La pâte doit reposer minimum 1h pour des crêpes plus légères.'}],
    },
    {
        'name': 'Soupe Minestrone',
        'description': 'Soupe italienne généreuse aux légumes, pâtes et haricots, repas complet.',
        'cuisine_type': 'Italienne', 'dish_type': 'Plat principal', 'category': 'Soupe',
        'diet': 'Vegan', 'ideal_season': 'Toutes saisons',
        'prep_time': 20, 'cook_time': 40, 'difficulty': 'Facile', 'servings': 6,
        'estimated_cost': '€', 'calories_per_serving': 240, 'proteins': 9, 'carbs': 38, 'fats': 6,
        'tags': ['soupe', 'légumes', 'vegan', 'italien', 'économique', 'complet'],
        'ingredients': [
            {'name': 'courgette', 'quantity': 2, 'unit': 'pièce', 'preparation': 'en dés'},
            {'name': 'carotte', 'quantity': 2, 'unit': 'pièce', 'preparation': 'en dés'},
            {'name': 'céleri', 'quantity': 2, 'unit': 'branche', 'preparation': 'en dés'},
            {'name': 'oignon', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'haricot blanc', 'quantity': 400, 'unit': 'g', 'preparation': 'en boîte, égouttés'},
            {'name': 'tomate concassée', 'quantity': 400, 'unit': 'g'},
            {'name': 'pâtes courtes', 'quantity': 150, 'unit': 'g'},
            {'name': 'bouillon de légumes', 'quantity': 1.5, 'unit': 'l'},
            {'name': 'ail', 'quantity': 2, 'unit': 'gousse'},
            {'name': 'huile d\'olive', 'quantity': 3, 'unit': 'cuillère à soupe'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Faire revenir oignon, ail, carotte et céleri dans l\'huile d\'olive 5 min.', 'duration': 5},
            {'step_number': 2, 'description': 'Ajouter courgettes, tomates, haricots et bouillon. Cuire 30 min.', 'duration': 30, 'technique': 'Mijoter'},
            {'step_number': 3, 'description': 'Ajouter les pâtes, cuire encore 10 min. Servir avec un filet d\'huile d\'olive.', 'duration': 10},
        ],
        'allergens': ['Gluten'], 'equipment': ['Grande casserole'],
        'tips': [{'tip_type': 'astuces', 'content': 'Ajouter une croûte de parmesan pendant la cuisson pour enrichir le bouillon.'}],
    },
    {
        'name': 'Lapin à la Moutarde',
        'description': 'Lapin mijoté dans une sauce crémeuse à la moutarde et aux herbes, plat rustique et savoureux.',
        'cuisine_type': 'Française', 'dish_type': 'Plat principal', 'category': 'Ragoût',
        'diet': 'Standard', 'ideal_season': 'Toutes saisons',
        'prep_time': 20, 'cook_time': 60, 'difficulty': 'Intermédiaire', 'servings': 4,
        'estimated_cost': '€€', 'calories_per_serving': 380, 'proteins': 42, 'carbs': 4, 'fats': 20,
        'tags': ['lapin', 'moutarde', 'mijoté', 'traditionnel', 'rustique'],
        'ingredients': [
            {'name': 'lapin', 'quantity': 1.5, 'unit': 'kg', 'preparation': 'découpé en morceaux'},
            {'name': 'moutarde à l\'ancienne', 'quantity': 3, 'unit': 'cuillère à soupe'},
            {'name': 'crème fraîche', 'quantity': 20, 'unit': 'cl'},
            {'name': 'vin blanc', 'quantity': 20, 'unit': 'cl'},
            {'name': 'échalote', 'quantity': 3, 'unit': 'pièce'},
            {'name': 'thym', 'quantity': 3, 'unit': 'branche'},
            {'name': 'laurier', 'quantity': 2, 'unit': 'feuille'},
            {'name': 'beurre', 'quantity': 30, 'unit': 'g'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Badigeonner les morceaux de lapin de moutarde. Faire dorer dans le beurre.', 'duration': 10, 'technique': 'Saisir'},
            {'step_number': 2, 'description': 'Ajouter les échalotes, déglacer au vin blanc. Ajouter thym et laurier. Mijoter 50 min à couvert.', 'duration': 50, 'technique': 'Mijoter'},
            {'step_number': 3, 'description': 'Retirer le lapin, incorporer la crème dans la sauce. Rectifier l\'assaisonnement.', 'duration': 5},
        ],
        'allergens': ['Lactose'], 'equipment': ['Cocotte'],
        'tips': [{'tip_type': 'accompagnements', 'content': 'Tagliatelles fraîches ou purée de pommes de terre'}, {'tip_type': 'accords', 'content': 'Bourgogne blanc'}],
    },
    {
        'name': 'Soufflé au Fromage',
        'description': 'Soufflé au comté, léger et aérien, servi immédiatement à la sortie du four.',
        'cuisine_type': 'Française', 'dish_type': 'Entrée', 'category': 'Autre',
        'diet': 'Végétarien', 'ideal_season': 'Toutes saisons',
        'prep_time': 20, 'cook_time': 30, 'difficulty': 'Difficile', 'servings': 4,
        'estimated_cost': '€€', 'calories_per_serving': 320, 'proteins': 18, 'carbs': 12, 'fats': 22,
        'tags': ['soufflé', 'fromage', 'végétarien', 'élégant', 'gastronomique'],
        'ingredients': [
            {'name': 'comté', 'quantity': 150, 'unit': 'g', 'preparation': 'râpé'},
            {'name': 'beurre', 'quantity': 50, 'unit': 'g'},
            {'name': 'farine', 'quantity': 40, 'unit': 'g'},
            {'name': 'lait', 'quantity': 30, 'unit': 'cl'},
            {'name': 'œuf', 'quantity': 4, 'unit': 'pièce', 'preparation': 'blancs et jaunes séparés'},
            {'name': 'muscade', 'quantity': 1, 'unit': 'pincée'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Préparer une béchamel épaisse. Hors du feu, incorporer les jaunes et le fromage.', 'duration': 10},
            {'step_number': 2, 'description': 'Monter les blancs en neige ferme avec une pincée de sel. Incorporer délicatement à la béchamel.', 'duration': 8, 'technique': 'Fouetter'},
            {'step_number': 3, 'description': 'Verser dans des ramequins beurrés et farinés. Cuire 25-30 min à 190°C SANS OUVRIR LE FOUR.', 'duration': 30, 'temperature': 190},
        ],
        'allergens': ['Gluten', 'Lactose', 'Œufs'], 'equipment': ['Four', 'Ramequins', 'Fouet'],
        'tips': [{'tip_type': 'erreurs', 'content': 'Ne jamais ouvrir le four pendant la cuisson !'}, {'tip_type': 'astuces', 'content': 'Servir immédiatement, le soufflé n\'attend pas.'}],
    },
    {
        'name': 'Boulettes de Viande à la Tomate',
        'description': 'Boulettes de bœuf moelleuses mijotées dans une sauce tomate aux herbes.',
        'cuisine_type': 'Italienne', 'dish_type': 'Plat principal', 'category': 'Pâtes',
        'diet': 'Standard', 'ideal_season': 'Toutes saisons',
        'prep_time': 20, 'cook_time': 35, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€', 'calories_per_serving': 420, 'proteins': 30, 'carbs': 22, 'fats': 22,
        'tags': ['bœuf', 'boulettes', 'sauce tomate', 'économique', 'famille'],
        'ingredients': [
            {'name': 'bœuf haché', 'quantity': 500, 'unit': 'g'},
            {'name': 'chapelure', 'quantity': 50, 'unit': 'g'},
            {'name': 'œuf', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'ail', 'quantity': 2, 'unit': 'gousse', 'preparation': 'haché'},
            {'name': 'tomate concassée', 'quantity': 800, 'unit': 'g'},
            {'name': 'oignon', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'basilic', 'quantity': 10, 'unit': 'feuille'},
            {'name': 'parmesan', 'quantity': 40, 'unit': 'g', 'preparation': 'râpé'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Mélanger bœuf, chapelure, œuf, ail haché, sel et poivre. Former des boulettes de 3 cm.', 'duration': 10},
            {'step_number': 2, 'description': 'Faire dorer les boulettes dans l\'huile sur toutes les faces. Réserver.', 'duration': 8, 'technique': 'Saisir'},
            {'step_number': 3, 'description': 'Faire revenir l\'oignon, ajouter les tomates. Mijoter 15 min. Remettre les boulettes 10 min.', 'duration': 25, 'technique': 'Mijoter'},
        ],
        'allergens': ['Gluten', 'Œufs', 'Lactose'], 'equipment': ['Poêle', 'Casserole'],
        'tips': [{'tip_type': 'accompagnements', 'content': 'Spaghetti ou polenta'}],
    },
    {
        'name': 'Banana Bread',
        'description': 'Cake moelleux aux bananes bien mûres, aux noix et à la cannelle. Zéro gaspillage !',
        'cuisine_type': 'Américaine', 'dish_type': 'Snack', 'category': 'Pâtisserie',
        'diet': 'Végétarien', 'ideal_season': 'Toutes saisons',
        'prep_time': 15, 'cook_time': 55, 'difficulty': 'Facile', 'servings': 8,
        'estimated_cost': '€', 'calories_per_serving': 280, 'proteins': 5, 'carbs': 38, 'fats': 13,
        'tags': ['banane', 'cake', 'moelleux', 'américain', 'anti-gaspillage', 'snack'],
        'ingredients': [
            {'name': 'banane', 'quantity': 3, 'unit': 'pièce', 'quality': 'très mûres, avec des taches noires'},
            {'name': 'farine', 'quantity': 200, 'unit': 'g'},
            {'name': 'sucre', 'quantity': 80, 'unit': 'g'},
            {'name': 'œuf', 'quantity': 2, 'unit': 'pièce'},
            {'name': 'beurre fondu', 'quantity': 80, 'unit': 'g'},
            {'name': 'levure chimique', 'quantity': 1, 'unit': 'cuillère à café'},
            {'name': 'cannelle', 'quantity': 1, 'unit': 'cuillère à café'},
            {'name': 'noix', 'quantity': 60, 'unit': 'g', 'preparation': 'concassées', 'optional': True},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Préchauffer le four à 175°C. Écraser les bananes à la fourchette.', 'duration': 5, 'temperature': 175},
            {'step_number': 2, 'description': 'Mélanger bananes, sucre, œufs et beurre fondu. Incorporer farine, levure et cannelle. Ajouter les noix.', 'duration': 5},
            {'step_number': 3, 'description': 'Verser dans un moule à cake. Cuire 50-55 min. Vérifier avec un couteau.', 'duration': 55, 'temperature': 175},
        ],
        'allergens': ['Gluten', 'Lactose', 'Œufs', 'Fruits à coque'], 'equipment': ['Four', 'Moule à cake'],
        'tips': [{'tip_type': 'astuces', 'content': 'Plus les bananes sont noires, plus le cake est moelleux et sucré.'}],
    },
    {
        'name': 'Salade César',
        'description': 'Salade croquante à la romaine avec croûtons, parmesan et sauce César crémeuse.',
        'cuisine_type': 'Américaine', 'dish_type': 'Plat principal', 'category': 'Salade',
        'diet': 'Standard', 'ideal_season': 'Toutes saisons',
        'prep_time': 20, 'cook_time': 10, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€€', 'calories_per_serving': 360, 'proteins': 18, 'carbs': 22, 'fats': 24,
        'tags': ['salade', 'césar', 'poulet', 'américain', 'croûtons'],
        'ingredients': [
            {'name': 'salade romaine', 'quantity': 2, 'unit': 'pièce'},
            {'name': 'blanc de poulet', 'quantity': 300, 'unit': 'g', 'preparation': 'grillé, en lamelles'},
            {'name': 'parmesan', 'quantity': 60, 'unit': 'g', 'preparation': 'en copeaux'},
            {'name': 'pain', 'quantity': 100, 'unit': 'g', 'preparation': 'en cubes, pour les croûtons'},
            {'name': 'anchois', 'quantity': 4, 'unit': 'filet'},
            {'name': 'jaune d\'œuf', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'ail', 'quantity': 1, 'unit': 'gousse'},
            {'name': 'moutarde', 'quantity': 1, 'unit': 'cuillère à café'},
            {'name': 'huile d\'olive', 'quantity': 8, 'unit': 'cuillère à soupe'},
            {'name': 'jus de citron', 'quantity': 2, 'unit': 'cuillère à soupe'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Faire dorer les cubes de pain à l\'huile d\'olive avec une gousse d\'ail.', 'duration': 8},
            {'step_number': 2, 'description': 'Sauce César : mixer anchois, jaune d\'œuf, moutarde, ail, citron. Ajouter l\'huile en filet pour émulsionner.', 'duration': 5},
            {'step_number': 3, 'description': 'Dresser la romaine, le poulet, les croûtons et le parmesan. Napper de sauce César.', 'duration': 5},
        ],
        'allergens': ['Gluten', 'Lactose', 'Œufs', 'Poisson'], 'equipment': ['Poêle', 'Mixeur', 'Saladier'],
        'tips': [],
    },
    {
        'name': 'Houmous Maison',
        'description': 'Tartinade crémeuse de pois chiches au tahini, citron et ail, servie avec des crudités.',
        'cuisine_type': 'Libanaise', 'dish_type': 'Snack', 'category': 'Sauce',
        'diet': 'Vegan', 'ideal_season': 'Toutes saisons',
        'prep_time': 10, 'cook_time': 0, 'difficulty': 'Facile', 'servings': 8,
        'estimated_cost': '€', 'calories_per_serving': 140, 'proteins': 6, 'carbs': 16, 'fats': 6,
        'tags': ['houmous', 'libanais', 'vegan', 'apéritif', 'économique', 'pois chiches'],
        'ingredients': [
            {'name': 'pois chiche', 'quantity': 400, 'unit': 'g', 'preparation': 'en boîte, égouttés'},
            {'name': 'tahini', 'quantity': 3, 'unit': 'cuillère à soupe'},
            {'name': 'citron', 'quantity': 1, 'unit': 'pièce', 'preparation': 'jus'},
            {'name': 'ail', 'quantity': 1, 'unit': 'gousse'},
            {'name': 'huile d\'olive', 'quantity': 3, 'unit': 'cuillère à soupe'},
            {'name': 'paprika', 'quantity': 0.5, 'unit': 'cuillère à café'},
            {'name': 'eau froide', 'quantity': 3, 'unit': 'cuillère à soupe'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Mixer tous les ingrédients jusqu\'à obtenir une texture lisse et crémeuse. Ajuster la consistance avec l\'eau froide.', 'duration': 5},
            {'step_number': 2, 'description': 'Dresser dans un bol, creuser un puit, verser un filet d\'huile d\'olive et saupoudrer de paprika.', 'duration': 2},
        ],
        'allergens': ['Sésame'], 'equipment': ['Mixeur'],
        'tips': [{'tip_type': 'astuces', 'content': 'Mixer longtemps (3-4 min) pour une texture ultra-crémeuse. L\'eau froide est le secret.'}, {'tip_type': 'accompagnements', 'content': 'Pain pita, crudités, falafels'}],
    },
    {
        'name': 'Magret de Canard au Miel',
        'description': 'Magret de canard poêlé, laqué au miel et vinaigre balsamique, rosé et croustillant.',
        'cuisine_type': 'Française', 'region': 'Sud-Ouest', 'dish_type': 'Plat principal',
        'category': 'Grillades', 'diet': 'Standard', 'ideal_season': 'Toutes saisons',
        'prep_time': 10, 'cook_time': 20, 'difficulty': 'Intermédiaire', 'servings': 2,
        'estimated_cost': '€€€', 'calories_per_serving': 480, 'proteins': 36, 'carbs': 16, 'fats': 28,
        'tags': ['canard', 'magret', 'miel', 'gastronomique', 'sud-ouest'],
        'ingredients': [
            {'name': 'magret de canard', 'quantity': 2, 'unit': 'pièce'},
            {'name': 'miel', 'quantity': 2, 'unit': 'cuillère à soupe'},
            {'name': 'vinaigre balsamique', 'quantity': 2, 'unit': 'cuillère à soupe'},
            {'name': 'thym', 'quantity': 2, 'unit': 'branche'},
            {'name': 'sel', 'quantity': 1, 'unit': 'au goût'},
            {'name': 'poivre', 'quantity': 1, 'unit': 'au goût'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Quadriller le côté gras des magrets. Assaisonner. Cuire côté peau à feu moyen 8-10 min en vidant la graisse régulièrement.', 'duration': 10, 'technique': 'Saisir'},
            {'step_number': 2, 'description': 'Retourner, cuire 5 min côté chair pour une cuisson rosée. Réserver sous papier alu.', 'duration': 5},
            {'step_number': 3, 'description': 'Déglacer la poêle avec miel et balsamique. Napper les magrets tranchés de cette sauce.', 'duration': 3, 'technique': 'Déglacer'},
        ],
        'allergens': [], 'equipment': ['Poêle'],
        'tips': [{'tip_type': 'astuces', 'content': 'Toujours commencer la cuisson à froid côté peau.'}, {'tip_type': 'accompagnements', 'content': 'Pommes sarladaises ou gratin dauphinois'}, {'tip_type': 'accords', 'content': 'Cahors ou Madiran'}],
    },
    {
        'name': 'Clafoutis aux Cerises',
        'description': 'Clafoutis traditionnel aux cerises, entre le flan et le gâteau, fondant et parfumé.',
        'cuisine_type': 'Française', 'region': 'Limousin', 'dish_type': 'Dessert',
        'category': 'Pâtisserie', 'diet': 'Végétarien', 'ideal_season': 'Printemps',
        'prep_time': 15, 'cook_time': 40, 'difficulty': 'Facile', 'servings': 6,
        'estimated_cost': '€', 'calories_per_serving': 240, 'proteins': 7, 'carbs': 34, 'fats': 9,
        'tags': ['printemps', 'cerise', 'clafoutis', 'dessert', 'traditionnel'],
        'ingredients': [
            {'name': 'cerise', 'quantity': 500, 'unit': 'g', 'preparation': 'avec ou sans noyaux'},
            {'name': 'lait', 'quantity': 30, 'unit': 'cl'},
            {'name': 'œuf', 'quantity': 3, 'unit': 'pièce'},
            {'name': 'sucre', 'quantity': 80, 'unit': 'g'},
            {'name': 'farine', 'quantity': 60, 'unit': 'g'},
            {'name': 'beurre', 'quantity': 20, 'unit': 'g'},
            {'name': 'sucre vanillé', 'quantity': 1, 'unit': 'sachet'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Préchauffer le four à 180°C. Beurrer un plat. Disposer les cerises.', 'duration': 5, 'temperature': 180},
            {'step_number': 2, 'description': 'Battre œufs, sucre, farine et sucre vanillé. Incorporer le lait progressivement pour une pâte lisse.', 'duration': 5},
            {'step_number': 3, 'description': 'Verser la pâte sur les cerises. Cuire 35-40 min.', 'duration': 40, 'temperature': 180},
        ],
        'allergens': ['Gluten', 'Lactose', 'Œufs'], 'equipment': ['Four', 'Plat à gratin', 'Saladier'],
        'tips': [{'tip_type': 'astuces', 'content': 'Le clafoutis traditionnel se fait avec les noyaux, qui parfument la pâte.'}],
    },
    {
        'name': 'Wok de Légumes Sautés',
        'description': 'Légumes colorés sautés au wok, sauce soja, gingembre et sésame — prêt en 15 min.',
        'cuisine_type': 'Japonaise', 'dish_type': 'Plat principal', 'category': 'Riz',
        'diet': 'Vegan', 'ideal_season': 'Toutes saisons',
        'prep_time': 15, 'cook_time': 10, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€', 'calories_per_serving': 180, 'proteins': 6, 'carbs': 22, 'fats': 8,
        'tags': ['wok', 'végétarien', 'rapide', 'légumes', 'asiatique', 'vegan'],
        'ingredients': [
            {'name': 'carotte', 'quantity': 2, 'unit': 'pièce', 'preparation': 'en julienne'},
            {'name': 'poivron', 'quantity': 2, 'unit': 'pièce', 'preparation': 'en lanières'},
            {'name': 'brocoli', 'quantity': 200, 'unit': 'g', 'preparation': 'en bouquets'},
            {'name': 'champignon', 'quantity': 150, 'unit': 'g', 'preparation': 'émincés'},
            {'name': 'ail', 'quantity': 2, 'unit': 'gousse'},
            {'name': 'gingembre frais', 'quantity': 15, 'unit': 'g'},
            {'name': 'sauce soja', 'quantity': 3, 'unit': 'cuillère à soupe'},
            {'name': 'huile de sésame', 'quantity': 1, 'unit': 'cuillère à soupe'},
            {'name': 'graines de sésame', 'quantity': 1, 'unit': 'cuillère à soupe'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Chauffer le wok à feu très vif. Faire sauter les légumes par ordre de cuisson : carotte, brocoli, poivron, champignons.', 'duration': 8, 'technique': 'Sauté'},
            {'step_number': 2, 'description': 'Ajouter ail et gingembre râpé. Assaisonner de sauce soja et huile de sésame. Servir avec riz et sésame.', 'duration': 2},
        ],
        'allergens': ['Soja', 'Sésame'], 'equipment': ['Wok'],
        'tips': [{'tip_type': 'astuces', 'content': 'Le secret du wok : feu maximal et légumes coupés fins pour une cuisson rapide uniforme.'}],
    },
    {
        'name': 'Terrine de Campagne',
        'description': 'Terrine de porc maison aux herbes et cognac, à préparer 2 jours à l\'avance.',
        'cuisine_type': 'Française', 'dish_type': 'Entrée', 'category': 'Autre',
        'diet': 'Standard', 'ideal_season': 'Toutes saisons',
        'prep_time': 30, 'cook_time': 90, 'rest_time': 2880, 'difficulty': 'Difficile', 'servings': 10,
        'estimated_cost': '€€', 'calories_per_serving': 320, 'proteins': 22, 'carbs': 3, 'fats': 24,
        'tags': ['terrine', 'porc', 'traditionnel', 'apéritif', 'à préparer à l\'avance'],
        'ingredients': [
            {'name': 'porc haché', 'quantity': 600, 'unit': 'g'},
            {'name': 'foie de porc', 'quantity': 200, 'unit': 'g', 'preparation': 'haché'},
            {'name': 'lardons', 'quantity': 150, 'unit': 'g'},
            {'name': 'échalote', 'quantity': 2, 'unit': 'pièce'},
            {'name': 'ail', 'quantity': 2, 'unit': 'gousse'},
            {'name': 'cognac', 'quantity': 3, 'unit': 'cuillère à soupe'},
            {'name': 'thym', 'quantity': 3, 'unit': 'branche'},
            {'name': 'laurier', 'quantity': 2, 'unit': 'feuille'},
            {'name': 'œuf', 'quantity': 2, 'unit': 'pièce'},
            {'name': 'crépine de porc', 'quantity': 1, 'unit': 'pièce'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Mélanger viandes, échalotes, ail, cognac, œufs, thym, sel et poivre. Laisser mariner 1h.', 'duration': 60},
            {'step_number': 2, 'description': 'Tapisser la terrine de crépine, remplir de farce. Disposer laurier sur le dessus.', 'duration': 10},
            {'step_number': 3, 'description': 'Cuire au bain-marie 1h30 à 170°C. Laisser refroidir sous presse. Réfrigérer 2 jours avant dégustation.', 'duration': 90, 'temperature': 170},
        ],
        'allergens': ['Œufs'], 'equipment': ['Four', 'Terrine avec couvercle', 'Plat bain-marie'],
        'tips': [{'tip_type': 'astuces', 'content': 'Plus elle repose, meilleure elle est. Idéalement 48h.'}, {'tip_type': 'accompagnements', 'content': 'Cornichons, pain de campagne'}, {'tip_type': 'accords', 'content': 'Beaujolais ou Côtes du Rhône'}],
    },

    # ── RECETTES SUPPLÉMENTAIRES ───────────────────────────────────────────
    {
        'name': 'Tarte à la Citrouille',
        'description': 'Tarte américaine à la courge épicée, crémeuse et parfumée à la cannelle.',
        'cuisine_type': 'Américaine', 'dish_type': 'Dessert', 'category': 'Pâtisserie',
        'diet': 'Végétarien', 'ideal_season': 'Automne',
        'prep_time': 20, 'cook_time': 50, 'difficulty': 'Intermédiaire', 'servings': 8,
        'estimated_cost': '€€', 'calories_per_serving': 280, 'proteins': 5, 'carbs': 36, 'fats': 13,
        'tags': ['automne', 'citrouille', 'tarte', 'américain', 'halloween'],
        'ingredients': [
            {'name': 'pâte brisée', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'courge', 'quantity': 500, 'unit': 'g', 'preparation': 'cuite et mixée en purée'},
            {'name': 'crème fraîche', 'quantity': 20, 'unit': 'cl'},
            {'name': 'cassonade', 'quantity': 100, 'unit': 'g'},
            {'name': 'œuf', 'quantity': 2, 'unit': 'pièce'},
            {'name': 'cannelle', 'quantity': 1, 'unit': 'cuillère à café'},
            {'name': 'gingembre', 'quantity': 0.5, 'unit': 'cuillère à café'},
            {'name': 'muscade', 'quantity': 0.5, 'unit': 'cuillère à café'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Préchauffer le four à 190°C. Foncer le moule de pâte brisée.', 'duration': 5, 'temperature': 190},
            {'step_number': 2, 'description': 'Mélanger purée de courge, crème, cassonade, œufs et épices. Verser sur la pâte.', 'duration': 5},
            {'step_number': 3, 'description': 'Cuire 45-50 min. Laisser refroidir avant de démouler.', 'duration': 50, 'temperature': 190},
        ],
        'allergens': ['Gluten', 'Lactose', 'Œufs'], 'equipment': ['Four', 'Moule à tarte'],
        'tips': [],
    },
    {
        'name': 'Ceviche de Saumon',
        'description': 'Saumon mariné dans le citron vert, oignon rouge, coriandre et piment — une fraîcheur d\'exception.',
        'cuisine_type': 'Mexicaine', 'dish_type': 'Entrée', 'category': 'Salade',
        'diet': 'Sans gluten', 'ideal_season': 'Été',
        'prep_time': 20, 'cook_time': 0, 'rest_time': 20, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€€€', 'calories_per_serving': 200, 'proteins': 24, 'carbs': 8, 'fats': 8,
        'tags': ['été', 'saumon', 'ceviche', 'frais', 'mexicain', 'sans gluten', 'rapide'],
        'ingredients': [
            {'name': 'saumon frais', 'quantity': 400, 'unit': 'g', 'preparation': 'en petits cubes', 'quality': 'sashimi grade'},
            {'name': 'citron vert', 'quantity': 4, 'unit': 'pièce', 'preparation': 'jus'},
            {'name': 'oignon rouge', 'quantity': 1, 'unit': 'pièce', 'preparation': 'finement émincé'},
            {'name': 'coriandre fraîche', 'quantity': 1, 'unit': 'botte'},
            {'name': 'piment', 'quantity': 1, 'unit': 'pièce', 'preparation': 'finement haché', 'optional': True},
            {'name': 'concombre', 'quantity': 0.5, 'unit': 'pièce', 'preparation': 'en petits dés'},
            {'name': 'avocat', 'quantity': 1, 'unit': 'pièce', 'preparation': 'en dés'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Faire mariner le saumon dans le jus de citron vert 20 min. La chair blanchit légèrement.', 'duration': 20},
            {'step_number': 2, 'description': 'Égoutter. Mélanger avec oignon, concombre, coriandre et piment. Ajouter l\'avocat au dernier moment.', 'duration': 5},
        ],
        'allergens': ['Poisson'], 'equipment': ['Saladier'],
        'tips': [{'tip_type': 'astuces', 'content': 'Utiliser impérativement du saumon de qualité sashimi-grade, très frais.'}],
    },
    {
        'name': 'Madeleine de Commercy',
        'description': 'Les authentiques madeleines moelleuses à la bosse bien formée, beurrées et citronnées.',
        'cuisine_type': 'Française', 'region': 'Lorraine', 'dish_type': 'Snack',
        'category': 'Pâtisserie', 'diet': 'Végétarien', 'ideal_season': 'Toutes saisons',
        'prep_time': 15, 'cook_time': 12, 'rest_time': 60, 'difficulty': 'Intermédiaire', 'servings': 24,
        'estimated_cost': '€', 'calories_per_serving': 110, 'proteins': 2, 'carbs': 14, 'fats': 5,
        'tags': ['madeleine', 'goûter', 'lorraine', 'biscuit', 'thé'],
        'ingredients': [
            {'name': 'œuf', 'quantity': 3, 'unit': 'pièce'},
            {'name': 'sucre', 'quantity': 150, 'unit': 'g'},
            {'name': 'farine', 'quantity': 200, 'unit': 'g'},
            {'name': 'beurre', 'quantity': 150, 'unit': 'g', 'preparation': 'fondu et noisette'},
            {'name': 'levure chimique', 'quantity': 1, 'unit': 'cuillère à café'},
            {'name': 'citron', 'quantity': 1, 'unit': 'pièce', 'preparation': 'zestes'},
            {'name': 'miel', 'quantity': 1, 'unit': 'cuillère à soupe'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Fouetter œufs, sucre et miel. Incorporer farine et levure. Ajouter le beurre noisette et les zestes. Réfrigérer 1h.', 'duration': 10, 'technique': 'Fouetter'},
            {'step_number': 2, 'description': 'Remplir les moules à madeleines beurrés aux 3/4. Cuire 11-12 min à 220°C. La bosse se forme grâce au choc thermique.', 'duration': 12, 'temperature': 220},
        ],
        'allergens': ['Gluten', 'Lactose', 'Œufs'], 'equipment': ['Four', 'Moule à madeleines', 'Fouet'],
        'tips': [{'tip_type': 'astuces', 'content': 'Le repos au froid + le four très chaud = la bosse caractéristique.'}],
    },
    {
        'name': 'Soupe de Légumes Verts',
        'description': 'Soupe légère et vitaminée aux légumes verts de printemps : courgette, épinard, petits pois.',
        'cuisine_type': 'Française', 'dish_type': 'Entrée', 'category': 'Soupe',
        'diet': 'Vegan', 'ideal_season': 'Printemps',
        'prep_time': 15, 'cook_time': 20, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€', 'calories_per_serving': 120, 'proteins': 5, 'carbs': 14, 'fats': 5,
        'tags': ['printemps', 'légumes verts', 'soupe', 'vegan', 'léger', 'détox'],
        'ingredients': [
            {'name': 'courgette', 'quantity': 2, 'unit': 'pièce', 'preparation': 'en dés'},
            {'name': 'épinard', 'quantity': 200, 'unit': 'g'},
            {'name': 'petits pois', 'quantity': 200, 'unit': 'g'},
            {'name': 'poireau', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'pomme de terre', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'bouillon de légumes', 'quantity': 1, 'unit': 'l'},
            {'name': 'huile d\'olive', 'quantity': 2, 'unit': 'cuillère à soupe'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Faire revenir le poireau dans l\'huile. Ajouter les légumes et le bouillon. Cuire 15 min.', 'duration': 18},
            {'step_number': 2, 'description': 'Ajouter les épinards, cuire 2 min. Mixer finement. Assaisonner.', 'duration': 4},
        ],
        'allergens': [], 'equipment': ['Casserole', 'Mixeur'],
        'tips': [],
    },
    {
        'name': 'Côtes de Porc aux Pommes',
        'description': 'Côtes de porc poêlées accompagnées de pommes caramélisées au beurre et thym.',
        'cuisine_type': 'Française', 'region': 'Normandie', 'dish_type': 'Plat principal',
        'category': 'Grillades', 'diet': 'Standard', 'ideal_season': 'Automne',
        'prep_time': 10, 'cook_time': 20, 'difficulty': 'Facile', 'servings': 4,
        'estimated_cost': '€€', 'calories_per_serving': 420, 'proteins': 32, 'carbs': 22, 'fats': 22,
        'tags': ['automne', 'porc', 'pomme', 'normand', 'rapide'],
        'ingredients': [
            {'name': 'côte de porc', 'quantity': 4, 'unit': 'pièce'},
            {'name': 'pomme', 'quantity': 3, 'unit': 'pièce', 'preparation': 'en quartiers', 'quality': 'Golden'},
            {'name': 'beurre', 'quantity': 40, 'unit': 'g'},
            {'name': 'thym', 'quantity': 3, 'unit': 'branche'},
            {'name': 'cidre', 'quantity': 15, 'unit': 'cl'},
            {'name': 'moutarde', 'quantity': 1, 'unit': 'cuillère à soupe'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Saisir les côtes de porc dans le beurre 5 min de chaque côté. Réserver.', 'duration': 10, 'technique': 'Saisir'},
            {'step_number': 2, 'description': 'Caraméliser les quartiers de pommes dans le même beurre. Déglacer au cidre.', 'duration': 5, 'technique': 'Déglacer'},
            {'step_number': 3, 'description': 'Remettre les côtes, ajouter la moutarde et le thym. Cuire 5 min à couvert.', 'duration': 5},
        ],
        'allergens': ['Lactose'], 'equipment': ['Poêle'],
        'tips': [{'tip_type': 'accords', 'content': 'Cidre brut de Normandie'}],
    },
    {
        'name': 'Ramen au Miso',
        'description': 'Soupe ramen japonaise au bouillon miso, nouilles, œuf mollet et légumes.',
        'cuisine_type': 'Japonaise', 'dish_type': 'Plat principal', 'category': 'Soupe',
        'diet': 'Standard', 'ideal_season': 'Hiver',
        'prep_time': 20, 'cook_time': 30, 'difficulty': 'Intermédiaire', 'servings': 4,
        'estimated_cost': '€€', 'calories_per_serving': 420, 'proteins': 22, 'carbs': 52, 'fats': 14,
        'tags': ['hiver', 'japonais', 'ramen', 'miso', 'soupe', 'réconfort'],
        'ingredients': [
            {'name': 'nouilles ramen', 'quantity': 400, 'unit': 'g'},
            {'name': 'pâte miso', 'quantity': 4, 'unit': 'cuillère à soupe'},
            {'name': 'bouillon de poule', 'quantity': 1.5, 'unit': 'l'},
            {'name': 'blanc de poulet', 'quantity': 200, 'unit': 'g'},
            {'name': 'œuf', 'quantity': 4, 'unit': 'pièce'},
            {'name': 'maïs', 'quantity': 100, 'unit': 'g'},
            {'name': 'nori', 'quantity': 4, 'unit': 'feuille'},
            {'name': 'ciboulette', 'quantity': 1, 'unit': 'botte'},
            {'name': 'gingembre', 'quantity': 15, 'unit': 'g'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Cuire les œufs 7 min pour un jaune coulant. Égoutter, peler.', 'duration': 10},
            {'step_number': 2, 'description': 'Chauffer le bouillon avec gingembre. Dissoudre le miso hors du feu.', 'duration': 10},
            {'step_number': 3, 'description': 'Cuire les nouilles, répartir dans des bols. Verser le bouillon miso, garnir de poulet émincé, maïs, œuf mollet coupé en deux, nori et ciboulette.', 'duration': 10},
        ],
        'allergens': ['Gluten', 'Soja', 'Œufs'], 'equipment': ['Casserole'],
        'tips': [{'tip_type': 'astuces', 'content': 'Ne pas faire bouillir le bouillon après avoir ajouté le miso pour préserver ses probiotiques.'}],
    },
    {
        'name': 'Tarte au Citron Meringuée',
        'description': 'Tarte au lemon curd fondant surmontée d\'une meringue légère et dorée.',
        'cuisine_type': 'Française', 'dish_type': 'Dessert', 'category': 'Pâtisserie',
        'diet': 'Végétarien', 'ideal_season': 'Toutes saisons',
        'prep_time': 45, 'cook_time': 25, 'rest_time': 60, 'difficulty': 'Difficile', 'servings': 8,
        'estimated_cost': '€€', 'calories_per_serving': 360, 'proteins': 6, 'carbs': 50, 'fats': 16,
        'tags': ['citron', 'tarte', 'meringue', 'pâtisserie', 'dessert'],
        'ingredients': [
            {'name': 'pâte sablée', 'quantity': 1, 'unit': 'pièce'},
            {'name': 'citron', 'quantity': 4, 'unit': 'pièce', 'preparation': 'jus et zestes'},
            {'name': 'œuf', 'quantity': 4, 'unit': 'pièce'},
            {'name': 'sucre', 'quantity': 200, 'unit': 'g'},
            {'name': 'beurre', 'quantity': 80, 'unit': 'g'},
            {'name': 'blanc d\'œuf', 'quantity': 3, 'unit': 'pièce'},
            {'name': 'sucre glace', 'quantity': 100, 'unit': 'g'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Cuire la pâte à blanc 15 min à 180°C.', 'duration': 15, 'temperature': 180},
            {'step_number': 2, 'description': 'Lemon curd : mélanger jus + zestes + œufs entiers + sucre. Épaissir à feu doux. Incorporer le beurre. Garnir le fond de tarte froid.', 'duration': 20},
            {'step_number': 3, 'description': 'Monter les blancs en neige avec le sucre glace. Couvrir la tarte. Dorer au chalumeau.', 'duration': 10, 'technique': 'Fouetter'},
        ],
        'allergens': ['Gluten', 'Lactose', 'Œufs'], 'equipment': ['Four', 'Moule à tarte', 'Casserole', 'Chalumeau'],
        'tips': [{'tip_type': 'astuces', 'content': 'Le lemon curd doit être bien froid avant de poser la meringue.'}],
    },
    {
        'name': 'Brandade de Morue',
        'description': 'Brandade provençale onctueuse à la morue dessalée, pommes de terre et huile d\'olive.',
        'cuisine_type': 'Française', 'region': 'Provence', 'dish_type': 'Plat principal',
        'category': 'Autre', 'diet': 'Standard', 'ideal_season': 'Toutes saisons',
        'prep_time': 20, 'cook_time': 30, 'rest_time': 1440, 'difficulty': 'Intermédiaire', 'servings': 4,
        'estimated_cost': '€€', 'calories_per_serving': 380, 'proteins': 28, 'carbs': 24, 'fats': 18,
        'tags': ['morue', 'brandade', 'provençal', 'poisson', 'pomme de terre'],
        'ingredients': [
            {'name': 'morue salée', 'quantity': 500, 'unit': 'g', 'preparation': 'dessalée 24h à l\'eau froide'},
            {'name': 'pomme de terre', 'quantity': 400, 'unit': 'g', 'preparation': 'cuite, en purée'},
            {'name': 'huile d\'olive', 'quantity': 10, 'unit': 'cl'},
            {'name': 'lait chaud', 'quantity': 10, 'unit': 'cl'},
            {'name': 'ail', 'quantity': 2, 'unit': 'gousse'},
            {'name': 'muscade', 'quantity': 1, 'unit': 'pincée'},
        ],
        'steps': [
            {'step_number': 1, 'description': 'Pocher la morue dessalée 10 min dans l\'eau. Égoutter, effeuiller en retirant la peau et les arêtes.', 'duration': 15},
            {'step_number': 2, 'description': 'Mixer la morue avec l\'ail. Incorporer alternativement huile d\'olive et lait chaud pour monter la brandade. Ajouter la purée de pommes de terre.', 'duration': 10},
            {'step_number': 3, 'description': 'Assaisonner de muscade, sel et poivre. Servir chaud avec des croûtons aillés.', 'duration': 5},
        ],
        'allergens': ['Poisson', 'Lactose'], 'equipment': ['Casserole', 'Mixeur'],
        'tips': [{'tip_type': 'astuces', 'content': 'Changer l\'eau de dessalage toutes les 8h.'}],
    },
]

count = 0
for recipe in recipes:
    try:
        add_recipe(recipe)
        count += 1
        print(f"✓ {recipe['name']}")
    except Exception as e:
        print(f"✗ {recipe['name']} : {e}")

print(f"\n{count}/{len(recipes)} recettes ajoutées !")
